### ISSUE TITLE
Error trying to get colors from <wallpaper file>

### ISSUE THREAD

**Issue by Prayag2** [luisbocanegra/kde-material-you-colors#11]
I downloaded the PKGBUILD, removed the `python-colr` dependency (see https://github.com/luisbocanegra/kde-material-you-colors/issues/10) and installed it using `makepkg -sic`. On running `kde-material-you-colors` in the terminal and chaning the wallpaper, it is showing an error: 
```
Wallpaper changed: /home/prayag/.local/share/wallpapers/chad.png
Unhandled exception. System.TypeInitializationException: The type initializer for 'SkiaSharp.SKData' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'SkiaSharp.SKObject' threw an exception.
 ---> System.InvalidOperationException: The version of the native libSkiaSharp library (80.2) is incompatible with this version of SkiaSharp. Supported versions of the native libSkiaSharp library are in the range [80.3, 81.0).
   at SkiaSharp.SkiaSharpVersion.CheckNativeLibraryCompatible(Version minSupported, Version current, Boolean throwIfIncompatible)
   at SkiaSharp.SkiaSharpVersion.CheckNativeLibraryCompatible(Boolean throwIfIncompatible)
   at SkiaSharp.SKObject..cctor()
   --- End of inner exception stack trace ---
   at SkiaSharp.SKData..cctor()
   --- End of inner exception stack trace ---
   at SkiaSharp.SKData.Create(Stream stream)
   at SkiaSharp.SKImage.FromEncodedData(Stream data)
   at Program.Main(String[] args)
Error trying to get colors from "/home/prayag/.local/share/wallpapers/chad.png"
```

**Comment by luisbocanegra** [comment]
I think this is because the package [skia-sharp](https://archlinux.org/packages/community/x86_64/skia-sharp/) has the version **2.80.3-1** but provides `libSkiaSharp.so=80.2.0-64`?
Can someone try copying the library `libSkiaSharp.so` from this repo to `/usr/lib/kde-material-you-colors/libSkiaSharp.so` to and test if it works? 
If it works maybe is a good idea to ship the library instead of depending on the skia-sharp package, downgrading it in this project may work too, we'll have to test this.

**Comment by luisbocanegra** [comment]
Should be fixed in: [v0.2.0BETA](https://github.com/luisbocanegra/kde-material-you-colors/releases/tag/v0.2.0BETA), (SkiaSharp library is now included) **not yet un AUR** please test:
```sh
mkdir kde-material-you-colors
cd kde-material-you-colors
curl https://raw.githubusercontent.com/luisbocanegra/kde-material-you-colors/testing/PKGBUILD -o PKGBUILD
makepkg -si
```
You will have to manually remove the now orphan `skia-sharp` package

**Comment by Prayag2** [comment]
It works now :D

**Comment by Kuchenmampfer** [comment]
Works for me too using these commands :)
> ```shell
> mkdir kde-material-you-colors
> cd kde-material-you-colors
> curl https://raw.githubusercontent.com/luisbocanegra/kde-material-you-colors/testing/PKGBUILD -o PKGBUILD
> makepkg -si
> ```

**Comment by luisbocanegra** [comment]
> Works for me too using these commands, thanks :)

It's now in the AUR ;)
