### ISSUE TITLE
option to disable opacity on light theme

### ISSUE THREAD

**Issue by ShatteredSkies** [luisbocanegra/kde-material-you-colors#121]
**Is your feature request related to a problem? Please describe.**
just have to say, while blur is absolutely beautiful on dark theme, it doesn't really look that impressive on light theme.
maybe there could be an option to disable it on light theme?

**Describe the solution you'd like**
an option that disables opacity on light theme by overwriting other opacity related options in the config file.

**Additional context**
With transparency on light theme:
![1](https://user-images.githubusercontent.com/56289692/206777580-b7570009-178c-496b-83e8-22105d231555.png)
the transparency effect looks pretty dull on light themes, especially on darker backgrounds

Without transparency on light theme:
![2](https://user-images.githubusercontent.com/56289692/206776833-3aefcd92-d274-484e-b17b-0ebfbee8e54c.png)
colors looks brighter and more colorful without transparency

**Comment by luisbocanegra** [comment]
I like the idea, lets split all the options for transparency into light and dark mode for consistency

**Comment by luisbocanegra** [comment]
A year later... 🙃 done

https://github.com/luisbocanegra/kde-material-you-colors/assets/15076387/ea254e79-6aa3-409d-9be4-b994a1a34fe4
