### ISSUE TITLE
Default text color is greyish and some colors are too intense

### ISSUE THREAD

**Issue by luisbocanegra** [luisbocanegra/kde-material-you-colors#122]
**Describe the bug**
pywal is kinda messed up

default text color is greyish and some colors are too intense (not sure if that is intentional)

**Screenshots**
![image](https://user-images.githubusercontent.com/56289692/206851013-e2751648-75aa-440e-aea1-a4d8b12453c8.png)

_Originally posted by @ShatteredSkies in https://github.com/luisbocanegra/kde-material-you-colors/issues/118#issuecomment-1345235713_

**Comment by luisbocanegra** [comment]
I did some changes in #119 that include:

- Intense (bold) text is now brighter for dark theme
- Intense (bold) text is now darker for light theme
- Colors from 1 to 7 are no longer sorted, didn't make much sense before and since we allow custom colors those are better off If they resemble the ANSI color scheme if one wants to put that in the colors list, like me :)

This is how it looks here, note that i have the option `Konsole > Profile edit > Appearance > Draw intense colors in bold font` enabled, probably didn't help that I didn't try with a lot of wallpapers and use opacity of 90% which of course looks worse on screenshots...

![Screenshot_20221210_050646](https://user-images.githubusercontent.com/15076387/206851957-834732e2-be77-4f62-b818-313a1fc72726.png)

***It seemed logical to me that bold text should stand up more, but normal text is too dark now?*** of course can be improved, open to suggestions, but let's discuss that in a separate issue :)

_Originally posted by @luisbocanegra in https://github.com/luisbocanegra/kde-material-you-colors/issues/118#issuecomment-1345244176_

**Comment by luisbocanegra** [comment]
Light version, I think it looks good enough, though it depends if the wallpaper has sufficient colors to work with

current:
![Screenshot_20221214_182115](https://user-images.githubusercontent.com/15076387/207743505-ba90b6bc-20d7-4a90-9296-3c127f736655.png)

on #119 
![Screenshot_20221214_182329](https://user-images.githubusercontent.com/15076387/207743708-2a21cd5e-84b6-4299-88e2-246e7daa0707.png)

main:
![Screenshot_20221214_182401](https://user-images.githubusercontent.com/15076387/207743820-c297b8be-ad9f-48f0-835b-ca3b539a5110.png)

i

**Comment by luisbocanegra** [comment]
Added to https://github.com/luisbocanegra/kde-material-you-colors/releases/tag/v1.5.0

**Comment by ShatteredSkies** [comment]
> I think it looks better now?

yeah, it does.
however, the greyish text still looks weird, especially for something like neofetch
![image](https://user-images.githubusercontent.com/56289692/207891423-e47bfc36-5cc7-457d-82d8-a747e55ebf17.png)

**Comment by luisbocanegra** [comment]
How about this?
![Screenshot_20221215_113535](https://user-images.githubusercontent.com/15076387/207929308-dbe7d679-c5ef-4326-a227-3f03d378622d.png)

**Comment by luisbocanegra** [comment]
Please try the https://github.com/luisbocanegra/kde-material-you-colors/tree/color-scheme-improvements branch (with light themes too, though I think these already looked good enough?)

**Comment by luisbocanegra** [comment]
Hmm, it could be brighter and kind of shifted to the secondary color, but not too much so it would be distinguishable from the other seven (actual) colors

> probably matching the titlebar color? 

The text? Have to verify but I think that one is actually darker

**Comment by ShatteredSkies** [comment]
> Hmm, it could be brighter and kind of shifted to the secondary color, but not too much so it would be distinguishable from the other seven (actual) colors
> 
yeah, that would be nice.
> > probably matching the titlebar color?
> 
> The text? Have to verify but I think that one is actually darker

huh, it actually looked just a bit darker than the titlebar text on my end. could be because of the font?

**Comment by luisbocanegra** [comment]
> > Hmm, it could be brighter and kind of shifted to the secondary color, but not too much so it would be distinguishable from the other seven (actual) colors
> 
> yeah, that would be nice.
> 
> > > probably matching the titlebar color?
> > 
> > 
> > The text? Have to verify but I think that one is actually darker
> 
> huh, it actually looked just a bit darker than the titlebar text on my end. could be because of the font?

Hmm, probably, or the transparency, I'm using 100 opaque rn

**Comment by luisbocanegra** [comment]
> > Hmm, it could be brighter and kind of shifted to the secondary color, but not too much so it would be distinguishable from the other seven (actual) colors
> 
> yeah, that would be nice.
> 

You can try again now (force pushed btw)

**Comment by ShatteredSkies** [comment]
> > > Hmm, it could be brighter and kind of shifted to the secondary color, but not too much so it would be distinguishable from the other seven (actual) colors
> > 
> > 
> > yeah, that would be nice.
> 
> You can try again now (force pushed btw)

looking nice with the tinted colors for the few wallpapers I tested.
