### ISSUE TITLE
Add option to reduce or increase brightness/contrast of theme

### ISSUE THREAD

**Issue by Heldaeus** [luisbocanegra/kde-material-you-colors#126]
**Is your feature request related to a problem? Please describe.**
The lbmultiplier and dbmultiplier options are great for creating themes with different levels of contrast between the background and foreground/text colors but often times when using a high factor of multiplication, especially with the light variant of a theme, the background saturation is too potent. There is no apparent option to ameliorate this whilst retaining a low contrast visual effect.

Here is an example of an appealing low contrast dark theme. (At least for me.)

![Screenshot_20221214_090932](https://user-images.githubusercontent.com/75914432/207638909-336b62ac-ab59-4c6d-8d83-d1c9ac54c5bf.png)

Now a low contrast light variant. (At least for me this far too bright.)

![Screenshot_20221214_091811](https://user-images.githubusercontent.com/75914432/207639206-58889bd7-3538-425b-80f7-92104512153f.png)

**Describe the solution you'd like**
 I propose splitting lbm/dbm into two options. Saturation and brightness. Below is the same screenshot as above with the UI selectively de-saturated via the hue/saturation adjustment in Photopea.

![Screenshot_20221214_091811-alt](https://user-images.githubusercontent.com/75914432/207640151-3d3844b1-7a25-4087-b91a-c2719acbf271.png)

If you measure the difference between the two you'll see that reducing the saturation in Photopea lowers or raises each color channel towards the average value between them all opposed to how this script seems to function by raising all channels towards white or black depending on if the theme is light or dark. If the user could choose their desired saturation level with lbm/dbm then choose a brightness level on a 0-4 scale per light and dark theme that would solve the issue of overly saturated themes. Additionally this would help when generating decent grey themes.

**Describe alternatives you've considered**
Using a lower factor of multiplication for lbm and dbm, while it does reduce the saturation of the seeded colors, does not offer dexterity over the brightness of the theme. I'm unable to achieve de-saturated middle toned themes, only saturated ones. I've attempted to use alternative colors with inherently less saturation and brightness for the seed but the script seems to favor hue and ignore sat/brightness in most cases.

**Comment by luisbocanegra** [comment]
> **Describe the solution you'd like** I propose splitting lbm/dbm into two options. Saturation and brightness. Below is the same screenshot as above with the UI selectively de-saturated via the hue/saturation adjustment in Photopea.
> 
> ![Screenshot_20221214_091811-alt](https://user-images.githubusercontent.com/75914432/207640151-3d3844b1-7a25-4087-b91a-c2719acbf271.png)
> 
> If you measure the difference between the two you'll see that reducing the saturation in Photopea lowers or raises each color channel towards the average value between them all opposed to how this script seems to function by raising all channels towards white or black depending on if the theme is light or dark. If the user could choose their desired saturation level with lbm/dbm then choose a brightness level on a 0-4 scale per light and dark theme that would solve the issue of overly saturated themes. Additionally this would help when generating decent grey themes.

> **Describe alternatives you've considered** Using a lower factor of multiplication for lbm and dbm, while it does reduce the saturation of the seeded colors, does not offer dexterity over the brightness of the theme. I'm unable to achieve de-saturated middle toned themes, only saturated ones. I've attempted to use alternative colors with inherently less saturation and brightness for the seed but the script seems to favor hue and ignore sat/brightness in most cases.

As is now this program gets the material you color **schemes** from the python port of material-color-utilities, as stated in the readme, by default those colors are what is best optimized for interface colors keeping (visibility, readability and accessibility). 

I decided to blend the background color against the primary color [40] dark, [70] light of the *tonal palette*, so themes didn't look too white/black, but other colors are still taken exactly like M3 scheme provides (accent, text), that's why it's limited.

Since changing the background too much would require adjusting everything and I didn't really want to deep dive in color science things, which would require me time to understand how to apply them well, I decided to keep things _simple_. 

But I really like the concept of allowing to customize how colors should look, similarly to the Dynamic Themes that android has where you can choose between different [variants](https://github.com/material-foundation/material-color-utilities/blob/main/java/scheme/Variant.java).

Also, I'm still a novice, this is my very first python project of this kind so I'm still learning. So will probably look int that but might be a very long term goal depending on how hard it turns out to implement.

**Comment by Heldaeus** [comment]
Perhaps a more convenient solution is to implement a saturation filter after the colors have been seeded?

I don't know if that would be more accessible but it would likely suffice.

**Comment by luisbocanegra** [comment]
Hmm, probably that could work

**Comment by luisbocanegra** [comment]
original:
![Screenshot_20221215_215250](https://user-images.githubusercontent.com/15076387/208018530-e4a01f36-643a-4477-a101-f67070a5652f.png)

1.5 saturation
![Screenshot_20221215_215346](https://user-images.githubusercontent.com/15076387/208018623-c809adbe-8b61-49b3-a2fc-4dda05bad449.png)

0.5 saturation
![Screenshot_20221215_215449](https://user-images.githubusercontent.com/15076387/208018691-8c4aa718-32b7-4664-9d3f-aeba060431e4.png)

**Comment by luisbocanegra** [comment]
light version for comparison:

![l_mode_contrast](https://user-images.githubusercontent.com/15076387/208027042-71c4c76d-a1c0-44e0-b30e-69410e2d4750.png)

**Comment by Heldaeus** [comment]
This looks promising. Even the 1.5x saturation doesn't look bad. I'm very interested in testing.

**Comment by luisbocanegra** [comment]
Please test the https://github.com/luisbocanegra/kde-material-you-colors/tree/saturation-and-brightness branch :)

Apart of the current blend option
```ini
# The amount of perceptible color for backgrounds in light mode
# A number between 0 and 4.0 (limited for accessibility purposes)
# Defaults to 1 if not set
light_blend_multiplier = 1

# The amount of perceptible color for backgrounds in dark mode
# A number between 0 and 4.0 (limited for accessibility purposes)
# Defaults to 1 if not set
dark_blend_multiplier = 1
```

It now has these controls
```ini

# The saturation of colors in light mode
# A number between TODO: set limits
# Defaults to 1 if not set
light_saturation_multiplier = 1

# The saturation of colors in dark mode
# A number between TODO: set limits
# Defaults to 1 if not set
dark_saturation_multiplier = 1

# The brightness of colors in light mode
# A number between TODO: set limits
# Defaults to 1 if not set
light_brightness_multiplier = 1

# The brightness of colors in dark mode
# A number between TODO: set limits
# Defaults to 1 if not set
dark_brightness_multiplier = 1
```
**Note: There are no limits for those new values yet, so hangs are expected**

**Comment by luisbocanegra** [comment]
❤️
![image](https://user-images.githubusercontent.com/15076387/208198683-97f7922c-7eaa-4a69-bb86-9f29c6acf9dd.png)

**Comment by Heldaeus** [comment]
Before:

![Screenshot_20221216_165019](https://user-images.githubusercontent.com/75914432/208218776-88e516ca-08be-4aa0-9405-7401a819439f.png)

After:

![Screenshot_20221216_165121](https://user-images.githubusercontent.com/75914432/208218853-f742fa7b-65ad-4fb3-8d92-cec9bb46885f.png)

I think the blue color was sampled from the shadows in the wallpaper but that color clearly isn't representative of the image. Like at all. But, with the saturation at 0.25x it fits the vibe better. I probably went too far with .25x though.

I need to play around with these settings more, but so far the sat options are awesome.

**Comment by luisbocanegra** [comment]
B/W or grayish images tend to return a default color, Pixel blue if I recall correctly, the algorithm in material-color-utilities discards the colors that aren't very suitable for generating themes, that could probably be changed but never looked into that.

**Comment by Heldaeus** [comment]
One thing I'm noticing is that colors look too bright when they're de-saturated. They don't share the same perceptual lightness as the saturated version. It's just bugging me. I figure that maybe a solution can be sought from the [Munsell color system](https://en.wikipedia.org/wiki/Munsell_color_system) but I know at that point you'd be delving into colorimetry which I know you're trying to tread lightly on. But, heres a graph anyways.

![image](https://user-images.githubusercontent.com/75914432/208327268-9cee49fb-8585-42b6-bc8f-24a29d939a0a.png)

I did some playing around with comparing the grey/color that the script produces vs Munsell and the Munsell color relationships I felt looked better and made more sense.

I'm not entirely sold on the brightness setting when it comes to darkening the colors.  It's too reminiscent of camera exposure for me, like it's compressing the foreground colors too much and they blend into the background. Lightening the colors seems fine though. I actually think the setting may be redundant since the color multiplier settings kind of achieve the same effect already.

Regarding dbm/lbm I've realized that the ratio of brightness between the 'view background' color and the 'window background' color in the 4x seed is larger than in the 1x.

Example:

![Screenshot_20221218_175310](https://user-images.githubusercontent.com/75914432/208326322-84c5d22d-9fbc-4657-8d8f-10f9ae37522c.jpg)

Vs what would be more consistent in my opinion.

![Screenshot_20221218_1753101](https://user-images.githubusercontent.com/75914432/208326354-459364cd-67e7-4cd0-95bf-a5373350e493.jpg)

This is kind of a nit pick though and not super important.

**Comment by luisbocanegra** [comment]
Tried to experiment with HCT by directly multiplying the chroma (saturation/colorfulness) on the generated palettes and here are the results. 

How does it look? I want to replace blend multiplier with it and then try to implement lightness (tone) control

![all](https://github.com/luisbocanegra/kde-material-you-colors/assets/15076387/febe8d06-82b9-4d1f-b949-7caefe2b15bf)

**Comment by luisbocanegra** [comment]
Different hue

![all-red](https://github.com/luisbocanegra/kde-material-you-colors/assets/15076387/61ad2e82-697e-4a44-b30a-714499cd56e0)

**Comment by luisbocanegra** [comment]
I think this is may be ready, thoughts?

![chroma](https://github.com/luisbocanegra/kde-material-you-colors/assets/15076387/66fd701d-a525-4487-a4b1-1a1fb00b25f4)
