### ISSUE TITLE
Add themed Cursors

### ISSUE THREAD

**Issue by metalune1** [luisbocanegra/kde-material-you-colors#13]
I would love for this to also modify the cursor colors, is this even a possibility? I might even look into it and try to do it myself

**Comment by luisbocanegra** [comment]
I don't know the process of making cursors, are these just images? If they are and there is a way to change the colors of images without losing quality it maay be possible... (I think they should of a single color like white). 
Also plasma got us covered with `plasma-apply-cursortheme` so we could swhitch them like schemes.

**Comment by Casul51** [comment]
I actually have no idea how to implement it easy way. Only make templates for each cursor, with hardcoded areas of applying specific color.


>  If they are and there is a way to change the colors of images without losing quality it maay be possible... (I think they will need to be of a single color like white).

  As mentioned, changing colors of already using cursors is really hit and miss, since they usually uses out of theming context.

**Comment by luisbocanegra** [comment]
Yeah, also I don't like the possibility of breaking  cursors just for the aesthetics
