### ISSUE TITLE
ModuleNotFoundError: No module named 'material_color_utilities_python' after python update

### ISSUE THREAD

**Issue by luisbocanegra** [luisbocanegra/kde-material-you-colors#139]
**Describe the bug**
The error appears after today's python 3.11 update on Arch, python-colr and python-pywal also stopped working

**Solution: Rebuild python-material-color-utilities AUR package or reinstall the pip package**
Example with paru `paru -S python-material-color-utilities --rebuild`

If you use python-colr (colored terminal hex colors) python-pywal (pywal integration) rebuild them too:
Example with paru `paru -S python-colr python-pywal --rebuild`

**Additional context**

**Comment by fwinn** [comment]
I've got the same problem with openSUSE Tumbleweed. Does anyone know how to solve it?

**Comment by marknefedov** [comment]
Yes they needed, but unfortunately currently I have no machine neither time to do this. Auto update service is not compatible with new project layout and suse tw moved to newer python version and dropped some packages.
Also it may be better to create a package from pipy version using https://en.opensuse.org/openSUSE:Packaging_Python

**Comment by Paradox-AT** [comment]
Hey I tried installing all packages but still it is crashing

`❯ yay -S python-material-color-utilities python-colr python-pywal16 kde-material-you-colors --rebuildtree`

[material-you-colors.log](https://github.com/user-attachments/files/18431644/material-you-colors.log)

**Comment by luisbocanegra** [comment]
@Paradox-AT `python-materialyoucolor-git` needs to be rebuilt too

**Comment by Paradox-AT** [comment]
> @Paradox-AT `python-materialyoucolor-git` needs to be rebuilt too

Thanks that worked, just needed to install `python-materialyoucolor-git`
