### ISSUE TITLE
theme_selector: apply_themes: No default theme found or currently active, skipping Plasma theming

### ISSUE THREAD

**Issue by yoshimario** [luisbocanegra/kde-material-you-colors#140]
**Describe the bug**
The command rund displays an error.
theme_selector: apply_themes: No default theme found or currently active, skipping Plasma theming

**To Reproduce**
ran command  kde-material-you-colors
```sh
[I] kde-material-you-colors: <module>: ###### STARTED NEW SESSION ######
[D] theme_selector: apply_themes: Config: {'light': None, 'file': None, 'monitor': 0, 'plugin': 'org.kde.image', 'ncolor': 0, 'iconslight': None, 'iconsdark': None, 'pywal': None, 'pywal_light': None, 'light_blend_multiplier': 1, 'dark_blend_multiplier': 1, 'on_change_hook': None, 'sierra_breeze_buttons_color': None, 'konsole_profile': None, 'titlebar_opacity': None, 'toolbar_opacity': None, 'konsole_opacity': None, 'color': None, 'klassy_windeco_outline': None, 'custom_colors_list': None, 'darker_window_list': None, 'use_startup_delay': None, 'startup_delay': 0}
[I] plasma_utils: get_initial_mode: Couldn't find theme by name, trying to resolve theme from last stored hash...
[D] plasma_utils: get_initial_mode: Config file hash:  080f3f8eac020ac566c252909d74ead45adfd52c
[D] plasma_utils: get_initial_mode: Dark scheme hash:  1dcea2f7317fe0708a6171bc75a525b36bc1ddde
[D] plasma_utils: get_initial_mode: Light scheme hash: 530c30e650f2ca78f9cfcf9e0841417c86a8d464
[I] theme_selector: apply_themes: Using source (image): /usr/share/wallpapers/garuda-wallpapers/remix-03.png
[I] m3_scheme_utils: get_color_schemes: Best colors: 0:#23294b,1:#301316,2:#28192a
[I] m3_scheme_utils: get_color_schemes: Using seed: 0:#23294b
[W] theme_selector: apply_themes: No default theme found or currently active, skipping Plasma theming
```
---------------------
**Expected behavior**
Should be able to use themes

**Screenshots**

**Desktop (please complete the following information):**
 - Operating System: Garuda Linux
  - KDE Plasma Version: 5.27.5
 - KDE Frameworks Version: 5.106.0
 - Qt Version:5.15.9
  - Graphics Platform: X11
 - Things in your system that might be relevant: [e.g. Kwin scripts, Plugins]

**Additional context**

**Comment by luisbocanegra** [comment]
This is a bug in the theme detection, it should fallback to dark mode the first time is used (without configuration/arguments). Will fix it in the next release.
Meanwhile you *should* be able to workaround it by selecting Material You Dark/Light color scheme from system settings, then it *should* work across reboots
