### ISSUE TITLE
Add translucency support

### ISSUE THREAD

**Issue by CavaleriOmar** [luisbocanegra/kde-material-you-colors#144]
Would support for toolbar transparency be possible for those using Klassy or Lightly as qt style?

For example
![Screenshot_2023 07 10-21e04](https://github.com/luisbocanegra/kde-material-you-colors/assets/54171779/c635d57d-661e-47ef-80ec-bf88918bd4dc)

**Comment by luisbocanegra** [comment]
There is support for that using `toolbar_opacity`
- With lightly Application style it should work automatically **note that some apps need to be re-opened to show transparency and kirigami based apps/views don't support transparency at all AFAIK**
- With Klassy application style you need to enable it in the Klassy window decoration settings even if you use other decoration **it should be possible to enable it automatically when transparency is requested**
  
  ![image](https://github.com/luisbocanegra/kde-material-you-colors/assets/15076387/4fa24f6c-f7a3-4eea-882e-9635c17eacfe)

- Lightly also supports sidebar transparency but as of now that value is not touched but it should also be possible to have as an option thing
