### ISSUE TITLE
cmake cmake typo in plasmoid scripts

### ISSUE THREAD

**Issue by Zren** [luisbocanegra/kde-material-you-colors#153]
Was skimming your code and noticed a copypasta typo:

`cmake cmake ...`

* https://github.com/luisbocanegra/kde-material-you-colors/blame/main/plasmoid/install.sh#L13
* https://github.com/luisbocanegra/kde-material-you-colors/blame/main/plasmoid/package-plasmoid.sh#L13

**Comment by luisbocanegra** [comment]
Fixed, thank you.
