### ISSUE TITLE
Changing icon themes doesn't work

### ISSUE THREAD

**Issue by Lilypad64** [luisbocanegra/kde-material-you-colors#155]
**Describe the bug**
The backend is trying to call "plasma-changeicon" to change icon themes, but the executable is in /usr/libexec instead of /usr/bin.

**To Reproduce**
1. Add "icondark" or "iconlight" to the config file or select icon themes in the KDE Widget.
2. Start the backend.

**Expected behavior**
Icon themes should be changed according to the config.

**Logs**
```
Traceback (most recent call last):
  File "/home/coffee/.local/bin/kde-material-you-colors", line 5, in <module>
    from kde_material_you_colors.main import main
  File "/home/coffee/.local/lib/python3.11/site-packages/kde_material_you_colors/main.py", line 338, in <module>
    main()
  File "/home/coffee/.local/lib/python3.11/site-packages/kde_material_you_colors/main.py", line 316, in main
    theme_selector.apply_themes(
  File "/home/coffee/.local/lib/python3.11/site-packages/kde_material_you_colors/theme_selector.py", line 139, in apply_themes
    plasma_utils.set_icons(
  File "/home/coffee/.local/lib/python3.11/site-packages/kde_material_you_colors/utils/plasma_utils.py", line 97, in set_icons
    changeicons_error = subprocess.check_output(
                        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '/usr/lib/plasma-changeicons Papirus-Dark' returned non-zero exit status 127.
```

**Desktop (please complete the following information):**
 - Operating System: Fedora 38
 - KDE Plasma Version: 5.27.4
 - KDE Frameworks Version: 5.109.0
 - Qt Version: 5.15.10
 - Graphics Platform: X11

**Comment by luisbocanegra** [comment]
Thanks for bringing this into my attention I used `/usr/lib/plasma-changeicons` because that's where it is located on arch but it shouldn't be hard-coded and I forgot to change it

Does the command `whereis plasma-changeicons` return the correct path for you?

**Comment by luisbocanegra** [comment]
> > Thanks for bringing this into my attention I used `/usr/lib/plasma-changeicons` because that's where it is located on arch but it shouldn't be hard-coded and I forgot to change it
> > Does the command `whereis plasma-changeicons` return the correct path for you?
> 
> `whereis plasma-changeicons` returns `plasma-changeicons: /usr/libexec/plasma-changeicons` for me. I am not sure if this is the case for my Fedora installation only.

Thanks, what matters is that it can be found :) so detecting where it is on any system through `whereis` when the backend starts should do the trick.

**Comment by luisbocanegra** [comment]
Fixed in https://github.com/luisbocanegra/kde-material-you-colors/pull/157
