### ISSUE TITLE
Doesn't change the color of the panel

### ISSUE THREAD

**Issue by hrqmonteiro** [luisbocanegra/kde-material-you-colors#158]
**Describe the bug**
The panel color is not affected

**To Reproduce**
Just run it

**Expected behavior**
For the panel to change colors

**Screenshots**

https://github.com/luisbocanegra/kde-material-you-colors/assets/17055027/5aecbee6-8bf3-4653-8870-51f1ea04075a

**Desktop (please complete the following information):**
 - Operating System: Manjaro
 - KDE Plasma Version: 5.27.8
 - KDE Frameworks Version: 5.110.0
 - Qt Version: 5.15.10
 - Graphics Platform: Wayland
 - Things in your system that might be relevant: Everything default

**Comment by luisbocanegra** [comment]
The default **Breeze Dark/Light** plasma themes have hard-coded colors, you need to use **Breeze** (_Follows color scheme_) or any other Plasma theme that supports color schemes.

**Comment by RhanCandia** [comment]
> The default **Breeze Dark/Light** plasma themes have hard-coded colors, you need to use **Breeze** (_Follows color scheme_) or any other Plasma theme that supports color schemes.

Hi there. Where can we get that Breeze theme that follows color scheme? I only see Breeze and Breeze Dark on mine and I didn't see it on the theme downloads.

**Comment by luisbocanegra** [comment]
> Hi there. Where can we get that Breeze theme that follows color scheme? I only see Breeze and Breeze Dark on mine and I didn't see it on the theme downloads.

System Settings > Colors & Themes > Plasma Style, it should come built-in with Plasma

![Image](https://github.com/user-attachments/assets/6832d5e8-caf6-4fc7-87d7-55591257f4fa)

If it's not there it could mean some Plasma Style you installed uses the same name for the folder or id (I think is called `default`) and is "replacing" the system one, if that's the case you need to remove it from `$HOME/.local/share/plasma/desktoptheme/`
