### ISSUE TITLE
Problem: nothing provides 'python3-material-color-utilities-python' needed by the to be installed kde-material-you-colors-1.5.1-lp154.34.1.noarch

### ISSUE THREAD

**Issue by guilloud** [luisbocanegra/kde-material-you-colors#160]
Hello,

I'm new to OpenSUSE, and not really good at understanding how everything works. I tried installing  according to the Readme file. The widget was easy to install, and then I tried to install the Backend but the zypper install kde-material-you-colors hasn't worked. This is what I get:
```
zypper install kde-material-you-colors
Loading repository data...
Reading installed packages...
Resolving package dependencies...

Problem: nothing provides 'python3-material-color-utilities-python' needed by the to be installed kde-material-you-colors-1.5.1-lp154.34.1.noarch
 Solution 1: do not install kde-material-you-colors-1.5.1-lp154.34.1.noarch
 Solution 2: break kde-material-you-colors-1.5.1-lp154.34.1.noarch by ignoring some of its dependencies

Choose from above solutions by number or cancel [1/2/c/d/?] (c): ?
```

I'm running this on my computer, and followed the instructions for the openSUSE 15.4
```
NAME="openSUSE Leap"
VERSION="15.5"
ID="opensuse-leap"
ID_LIKE="suse opensuse"
VERSION_ID="15.5"
PRETTY_NAME="openSUSE Leap 15.5"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:leap:15.5"
BUG_REPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://www.opensuse.org/"
DOCUMENTATION_URL="https://en.opensuse.org/Portal:Leap"
LOGO="distributor-logo-Leap"
```

Many thanks if someone can help me.

**Comment by luisbocanegra** [comment]
Hi,

It looks like `python3-material-color-utilities-python` package is not built for your distro in that repo, which is voluntarily maintained by https://github.com/marknefedov, maybe they have some insight of why is it like that?

Also noticed they haven't updated the package to the latest version yet so maybe we should ask [here](https://github.com/luisbocanegra/kde-material-you-colors/discussions/134) if they still want to continue doing so, it _shouldn't_ be much of a problem now that the project is a python package but is up to them :)

For now, you may want to install the package using `pip`/`pipx` 

**OR** manually in a virtual python environment like this:

**Please change `/tmp/testenv` to the path you want to install the virtual environment, /tmp content is deleted on reboot**

```sh
$ mkdir /tmp/testenv && cd /tmp/testenv

# Create a python virtual environment
$ python -m venv /tmp/testenv

# Activate the environment for this shell
$ source /tmp/testenv/bin/activate

# install the package inside the environment
# you may also install other optional python modules in this step, like pywal
$ pip install kde-material-you-colors

# deactivate the python environment
$ deactivate

# Copy the desktop entries, and create a symbolic link to ~/.local/bin 
/tmp/testenv/bin/kde-material-you-colors -cl

# Now you can run outside the virtual environment and even enable autostart

kde-material-you-colors -a
```

**Comment by blobcatz** [comment]
`python-material-color-utilities-python` is [available in openSUSE Factory repo](https://software.opensuse.org//download.html?project=openSUSE%3AFactory&package=python-material-color-utilities-python) with `python311-material-color-utilities-python`

**Comment by luisbocanegra** [comment]
> `python-material-color-utilities-python` is [available in openSUSE Factory repo](https://software.opensuse.org//download.html?project=openSUSE%3AFactory&package=python-material-color-utilities-python) with `python311-material-color-utilities-python`

Thanks for letting us know.

I have contacted the maintainer in the relevant [discussion](https://github.com/luisbocanegra/kde-material-you-colors/discussions/134) about this issue and whether or not they still want to maintain the packages, so we'll see.
