### ISSUE TITLE
Plasma 6 support

### ISSUE THREAD

**Issue by luisbocanegra** [luisbocanegra/kde-material-you-colors#161]
- [x] plasmoid [needs porting](https://develop.kde.org/docs/plasma/widget/porting_kf6/)
## Backend
- Getting wallpaper with screenshot needs porting:
	- [x] Loaded script object path has changed `/{id}` > `/Scripting/Script{id}`
	- [x] KWin script to get window handle: `workspace.clientList()` > `workspace.windowList()`. 
	- [x] Looks like `window.caption` may no longer be set for the desktop, so another property (or combination of them) needs to be used to find Desktop windows
	- [x] `window.screen` was also lost, matching is now done by first sorting the screens (triple+ monitors and non-horizontal arrangements untested)

**Comment by archisman-panigrahi** [comment]
In case the theme has been ported to Plasma 6, can you please release a new version?

**Comment by luisbocanegra** [comment]
I an busy with other things at the moment, If you want to help catch bugs please try installing it manually.

The backend can be run using these commands but it would be better if you try in a virtual environment with all the dependencies there.
```
export PYTHONPATH="$PWD/src:$PYTHONPATH"
python -m kde_material_you_colors.main
```

**Comment by luisbocanegra** [comment]
So it appears that sorting the desktop windows for the screenshot method isn't needed at all, trying multiple horizontal and vertical arrangements and it always gets the window of the correct screen number given by the panel.
