### ISSUE TITLE
Can't install on Debian

### ISSUE THREAD

**Issue by user-naa** [luisbocanegra/kde-material-you-colors#178]
Error while install trough pipx:
```
sasha@DESKTOP-HOME:~$ pipx install kde-material-you-colors
Fatal error from pip prevented installation. Full pip output in file:
    /home/sasha/.local/pipx/logs/cmd_2024-01-12_18.10.22_pip_errors.log

pip seemed to fail to build package:
    dbus-python>=1.3.2

Some possibly relevant errors from pip install:
    error: subprocess-exited-with-error
    ../subprojects/dbus-gmain/meson.build:107:11: ERROR: Dependency lookup for dbus-1 with method 'pkgconfig' failed: Pkg-config for machine host machine not found. Giving up.
    error: metadata-generation-failed

Error installing kde-material-you-colors.
```
OS: Debian 12 (bookworm)

**Comment by luisbocanegra** [comment]
`apt install python-dbus-dev libglib2.0-dev`

**Comment by luisbocanegra** [comment]
> Thank you! I installed, but service doesn't starting:
> 
> ```
> ❯ ~/.local/bin/kde-material-you-colors
> [D] utils: kill_existing: Found previous process in PID file: '6902' killing...
> [I] main: main: ###### STARTED NEW SESSION ######
> [D] main: main: Installed in /home/sasha/.local/pipx/venvs/kde-material-you-colors/lib/python3.11/site-packages/kde_material_you_colors
> [D] config: eval_conf: Config "iconslight": empty, using fallback: None
> [D] config: eval_conf: Config "iconsdark": empty, using fallback: None
> [D] config: eval_conf: Config "on_change_hook": empty, using fallback: None
> [D] config: eval_conf: Config "color": empty, using fallback: None
> [D] config: eval_conf: Config "custom_colors_list": empty, using fallback: None
> [D] config: eval_conf: Config "darker_window_list": empty, using fallback: None
> [E] kwin_utils: get_desktop_window_id: Script id 0 didn't return a desktop id for screen 0: Command '['journalctl', '--since', '2024-01-13 19:50:17', '--user', '-u', 'plasma-kwin_wayland.service', '--output', 'cat', '-g', 'js: KMYC-desktop-window-id']' returned non-zero exit status 1.
> Traceback (most recent call last):
>   File "/home/sasha/.local/pipx/venvs/kde-material-you-colors/lib/python3.11/site-packages/kde_material_you_colors/utils/kwin_utils.py", line 147, in get_desktop_window_id
>     result = subprocess.run(
>              ^^^^^^^^^^^^^^^
>   File "/usr/lib/python3.11/subprocess.py", line 571, in run
>     raise CalledProcessError(retcode, process.args,
> subprocess.CalledProcessError: Command '['journalctl', '--since', '2024-01-13 19:50:17', '--user', '-u', 'plasma-kwin_wayland.service', '--output', 'cat', '-g', 'js: KMYC-desktop-window-id']' returned non-zero exit status 1.
> [E] wallpaper_utils: get_desktop_screenshot: Command 'Command '['journalctl', '--since', 'TIME_NOW', '--user', '-u', 'plasma-kwin_wayland.service', '--output', 'cat', '-g', 'js: KMYC-desktop-window-id']' returned non-zero exit status 1.' returned non-zero exit status 1.
> [E] wallpaper_utils: reload: Command 'Command '['journalctl', '--since', 'TIME_NOW', '--user', '-u', 'plasma-kwin_wayland.service', '--output', 'cat', '-g', 'js: KMYC-desktop-window-id']' returned non-zero exit status 1.' returned non-zero exit status 1.
> [W] main: main: Screenshot mode enabled, Waiting 900.0s between updates
> [D] main: main: {'light': False, 'file': None, 'monitor': 0, 'ncolor': 0, 'iconslight': None, 'iconsdark': None, 'pywal': True, 'pywal_light': False, 'light_blend_multiplier': 1.0, 'dark_blend_multiplier': 1.0, 'on_change_hook': None, 'sierra_breeze_buttons_color': False, 'disable_konsole': False, 'titlebar_opacity': 100, 'titlebar_opacity_dark': 100, 'toolbar_opacity': 100, 'toolbar_opacity_dark': 100, 'konsole_opacity': 100, 'konsole_opacity_dark': 100, 'color': None, 'klassy_windeco_outline': False, 'custom_colors_list': None, 'darker_window_list': None, 'use_startup_delay': False, 'startup_delay': 0, 'plasma_follows_scheme': False, 'pywal_follows_scheme': False, 'main_loop_delay': 1.0, 'screenshot_delay': 900.0, 'once_after_change': False, 'pause_mode': False}
> [E] kwin_utils: get_desktop_window_id: Script id 0 didn't return a desktop id for screen 0: Command '['journalctl', '--since', '2024-01-13 19:50:17', '--user', '-u', 'plasma-kwin_wayland.service', '--output', 'cat', '-g', 'js: KMYC-desktop-window-id']' returned non-zero exit status 1.
> Traceback (most recent call last):
>   File "/home/sasha/.local/pipx/venvs/kde-material-you-colors/lib/python3.11/site-packages/kde_material_you_colors/utils/kwin_utils.py", line 147, in get_desktop_window_id
>     result = subprocess.run(
>              ^^^^^^^^^^^^^^^
>   File "/usr/lib/python3.11/subprocess.py", line 571, in run
>     raise CalledProcessError(retcode, process.args,
> subprocess.CalledProcessError: Command '['journalctl', '--since', '2024-01-13 19:50:17', '--user', '-u', 'plasma-kwin_wayland.service', '--output', 'cat', '-g', 'js: KMYC-desktop-window-id']' returned non-zero exit status 1.
> [E] wallpaper_utils: get_desktop_screenshot: Command 'Command '['journalctl', '--since', 'TIME_NOW', '--user', '-u', 'plasma-kwin_wayland.service', '--output', 'cat', '-g', 'js: KMYC-desktop-window-id']' returned non-zero exit status 1.' returned non-zero exit status 1.
> [E] wallpaper_utils: reload: Command 'Command '['journalctl', '--since', 'TIME_NOW', '--user', '-u', 'plasma-kwin_wayland.service', '--output', 'cat', '-g', 'js: KMYC-desktop-window-id']' returned non-zero exit status 1.' returned non-zero exit status 1.
> [I] main: main: Wallpaper: org.kde.image (screenshot): None
> [E] kwin_utils: get_desktop_window_id: Script id 0 didn't return a desktop id for screen 0: Command '['journalctl', '--since', '2024-01-13 19:50:18', '--user', '-u', 'plasma-kwin_wayland.service', '--output', 'cat', '-g', 'js: KMYC-desktop-window-id']' returned non-zero exit status 1.
> Traceback (most recent call last):
>   File "/home/sasha/.local/pipx/venvs/kde-material-you-colors/lib/python3.11/site-packages/kde_material_you_colors/utils/kwin_utils.py", line 147, in get_desktop_window_id
>     result = subprocess.run(
>              ^^^^^^^^^^^^^^^
>   File "/usr/lib/python3.11/subprocess.py", line 571, in run
>     raise CalledProcessError(retcode, process.args,
> subprocess.CalledProcessError: Command '['journalctl', '--since', '2024-01-13 19:50:18', '--user', '-u', 'plasma-kwin_wayland.service', '--output', 'cat', '-g', 'js: KMYC-desktop-window-id']' returned non-zero exit status 1.
> ```

You're welcome. Oh that's bug https://github.com/luisbocanegra/kde-material-you-colors/issues/180. Wayland with a wallpaper that doesn't require desktop screenshot (bug https://github.com/luisbocanegra/kde-material-you-colors/issues/179) should work.

**Comment by user-naa** [comment]
My PC very bad works with Wayland. So I am using X11.

**Comment by luisbocanegra** [comment]
I have added the packages to the readme. Also the latest release fixes the error you reported here but requires compiling a small helper, [install instructions here](https://github.com/luisbocanegra/kde-material-you-colors#desktop-screenshot-helper-support-for-all-wallpaper-plugins).
