### ISSUE TITLE
Using pipx, kde-material-you-colors does not work with pywal (both installed by pipx)

### ISSUE THREAD

**Issue by dawetmaster** [luisbocanegra/kde-material-you-colors#183]
**Describe the bug**
With kde-material-you-colors and pywal both installed by pipx, the log shows "Pywal option enabled but python module is not installed, ignored" when run.

**To Reproduce**
1. Install kde-material-you-colors and pywal using pipx by running script 
```
pipx install kde-material-you-colors
pipx install pywal
```
2. Check if both kde-material-you-colors and wal exist as linked file in ~/.local/bin
3. Check if 'Apply to pywal' is checked on the KDE applet or just run `kde-material-you-colors -wal` using command line
4. See warning log shown with text "Pywal option enabled but python module is not installed, ignored".

**Expected behavior**
Pywal must be detected and used, but instead kde-material-you-colors does not detect pywal. It seems pywal and kde-material-you-colors is under a different environment.

**Screenshots**
![image](https://github.com/luisbocanegra/kde-material-you-colors/assets/71202342/5980f4ba-3d5b-4d85-b515-e4f66d6ad128)

**Desktop (please complete the following information):**
 - Operating System: Fedora 39
 - KDE Plasma Version: 5.27.10
 - KDE Frameworks Version: 5.113.0
 - Qt Version: 5.15.12
 - Graphics Platform: Wayland

**Temporary solution**
Run this command
```bash
/home/<username>/.local/share/pipx/venvs/kde-material-you-colors/bin/python -m pip --no-input install pywal
```
And run kde-material-you-colors once again. It will work.

**Comment by luisbocanegra** [comment]
> **Describe the bug** With kde-material-you-colors and pywal both installed by pipx, the log shows "Pywal option enabled but python module is not installed, ignored" when run.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
>     1. Install kde-material-you-colors and pywal using pipx by running script
> 
> 
> ```
> pipx install kde-material-you-colors
> pipx install pywal
> ```
> 
>     2. Check if both kde-material-you-colors and wal exist as linked file in ~/.local/bin
> 
>     3. Check if 'Apply to pywal' is checked on the KDE applet or just run `kde-material-you-colors -wal` using command line
> 
>     4. See warning log shown with text "Pywal option enabled but python module is not installed, ignored".
> 
> 
> **Expected behavior** Pywal must be detected and used, but instead kde-material-you-colors does not detect pywal. It seems pywal and kde-material-you-colors is under a different environment.

You're right, it's installed in a separate environment, the solution would be to use pipx's [package injection](https://pipx.pypa.io/stable/#inject-a-package) to add Pywal to kde-material-you-colors environment

```
pipx install kde-material-you-colors
pipx inject kde-material-you-colors pywal
```

**Comment by dawetmaster** [comment]
Thank you. Can I write a merge request on readme.md?

**Comment by luisbocanegra** [comment]
> Thank you. Can I write a merge request on readme.md? Edit: It's working now!

Of course!

**Comment by dawetmaster** [comment]
Check it out here https://github.com/luisbocanegra/kde-material-you-colors/pull/185
Thank you for this useful project!

**Comment by luisbocanegra** [comment]
> Check it out here #185 

Merged 👍 

> Thank you for this useful project!

You're welcome!
