### ISSUE TITLE
Compatibility Issue: LibreOffice and OpenRGB Not Adhering to Material Color Theme in KDE Plasma

### ISSUE THREAD

**Issue by Maxinova** [luisbocanegra/kde-material-you-colors#189]
Description:
Some applications, such as LibreOffice and OpenRGB, deviate from the expected color scheme set by Material You Colors in KDE Plasma. Despite selecting the appropriate color theme in KDE settings, these applications consistently use light colors instead of adhering to the desired dark theme. Restoring the default Breeze color theme resolves this inconsistency.

Steps to Reproduce:

- Install and activate Material You Colors.
- Ensure the corresponding color theme is selected in KDE settings.
- Launch LibreOffice or OpenRGB.
- Observe that the applications do not adhere to the selected color pattern and continue to use light colors.

Expected Behavior:
Applications should adopt the dark theme provided by Material You Colors, similar to their behavior when using the default Breeze color theme.

System Information:

- Operating System: Arch Linux
- KDE Plasma Version: 6.0.1
- KDE Frameworks Version: 6.0.0
- Qt Version: 6.6.2
- Graphics Platform: Wayland

**Comment by luisbocanegra** [comment]
Can't reproduce, for me these two installed as system package (Arch repos) work just fine. They launch with the current active color scheme and update when colors change.

**Comment by luisbocanegra** [comment]
> Here is a video demonstrating the issue. I switch between the default Breeze theme and Material You dark theme. As you can see, both LibreOffice and OpenRGB do not adhere to the dark theme with Material You dark. They are both installed as system packages.
> 2024-03-13.14-54-06.webm

Still can't reproduce, looks like you could be missing some package that is in charge of updating the colors of those apps. Please check that:

- Breeze is set as the GTK theme
- You don't have any other tool that could be interfering with qt theming like kvantum or qt5/6ct 

> P.S.: You can also notice that all Material You color themes are duplicated. Is this normal?

Yes that's expected. Why is it like that is explained in the readme here https://github.com/luisbocanegra/kde-material-you-colors?tab=readme-ov-file#notes
