### ISSUE TITLE
How do you change the system tray icons?

### ISSUE THREAD

**Issue by TheSnowfield** [luisbocanegra/kde-material-you-colors#196]
Your theme is insanely beautiful, I'd like to know how you change the KDE system tray icons.

I'm using KDE Plasma 5, I tried to modify the SVG icons under `/usr/share/icons/breeze-dark/status` and got no icon changed on the system tray, It keeps ugly :(
![image](https://github.com/luisbocanegra/kde-material-you-colors/assets/17957399/3138fd58-4048-4f2a-a36a-ce6b9ebdfd07)

Sorry for this issue I can't find an email address to contact you,
I'm looking forward to your reply! Heartly thanks!

Cheers.

**Comment by luisbocanegra** [comment]
> Your theme is insanely beautiful 

Thanks!

> I'd like to know how you change the KDE system tray icons.

On plasma 5 Panel icons are provided by the plasma theme, if the theme you are using doesn't have custom icons the default icons from Breeze theme are used `/usr/share/plasma/desktoptheme/default/icons/`. In the showcased screenshots I was using a modified https://github.com/doncsugar/lightly-plasma with icons taken from either [arc-kde](https://github.com/PapirusDevelopmentTeam/arc-kde) or [materia-kde](https://github.com/PapirusDevelopmentTeam/materia-kde), I also use my own fork of https://github.com/luisbocanegra/papirus-colors that works better with `kde-material-you-colors` 

On plasma 6 all icons come from the icon theme, I use [Papirus icon theme](https://github.com/PapirusDevelopmentTeam/papirus-icon-theme) (git version from AUR as plasma 6 support is still being worked on)

**Comment by TheSnowfield** [comment]
Thanks for your quick reply! 
I realized the huge difference between Plasma 5 and 6. I'm a Plasma 5 user, I've been misled in Plasma 6 way. Thanks for clarifying all this!

Have a nice day!
