### ISSUE TITLE
KDE Store Version Mismatch

### ISSUE THREAD

**Issue by nr128** [luisbocanegra/kde-material-you-colors#202]
Related to Commit: Bump versions backend 1.9.0 & plasmoid 0.4.0

Plasmoid version was updated last night to 0.4.0, store version is still   0.3.0

Link to store: https://store.kde.org/p/2136963

**Comment by luisbocanegra** [comment]
Haven't made a release yet. I was busy trying to build [distribution packages](https://build.opensuse.org/project/show/home:luisbocanegra) but there are some problems with Fedora 40 so I will try publishing on Fedora’s User Repository instead. When that is ready I will make the release and update KDE Store, PyPI, AUR

**Comment by luisbocanegra** [comment]
Released https://github.com/luisbocanegra/kde-material-you-colors/releases/tag/v1.9.1 and KDE Store updated
