### ISSUE TITLE
Can't run 1.9.1

### ISSUE THREAD

**Issue by Graninius** [luisbocanegra/kde-material-you-colors#206]
I got an error **Backend is not running. This Plasmoid requires [kde-material-you-colors](https://github.com/luisbocanegra/kde-material-you-colors) to be installed and running to work** after 1.9.1 update.
- updated to vers.1.9.1 from AUR
- updated plasmoid to vers.0.4.1
The console output:
```
❯ kde-material-you-colors -v
1.9.1
❯ kde-material-you-colors
Traceback (most recent call last):
  File "/home/xxxi/.local/bin/kde-material-you-colors", line 5, in <module>
    from kde_material_you_colors.main import main
  File "/usr/lib/python3.12/site-packages/kde_material_you_colors/main.py", line 507, in <module>
    main()
  File "/usr/lib/python3.12/site-packages/kde_material_you_colors/main.py", line 354, in main
    from .config import Configs
  File "/usr/lib/python3.12/site-packages/kde_material_you_colors/config.py", line 4, in <module>
    from kde_material_you_colors.utils import color_utils
  File "/usr/lib/python3.12/site-packages/kde_material_you_colors/utils/color_utils.py", line 5, in <module>
    from materialyoucolor.blend import Blend
ModuleNotFoundError: No module named 'materialyoucolor'
```
Manjaro KDE, unstable
KDE 6.0.4
Frameworks 6.2.0
Qt 6.7.0
Wayland

**Comment by ShatteredSkies** [comment]
#191 install ```python-materialyoucolor``` from the AUR

**Comment by Graninius** [comment]
> #191 install `python-materialyoucolor` from the AUR

```
❯ kde-material-you-colors
[D] utils: kill_existing: Found previous process in PID file: '43479' killing...
[D] utils: kill_existing: Process not found, probably ended by someone else
[I] main: main: ###### STARTED NEW SESSION ######
[D] main: main: Installed in /usr/lib/python3.12/site-packages/kde_material_you_colors
[D] config: eval_conf: Config "on_change_hook": empty, using fallback: None
[D] config: eval_conf: Config "color": empty, using fallback: None
[D] config: eval_conf: Config "custom_colors_list": empty, using fallback: None
[D] config: eval_conf: Config "darker_window_list": empty, using fallback: None
[D] config: eval_conf: Config "qdbus_executable": empty, using fallback: None
[D] main: main: {'light': True, 'file': None, 'monitor': 0, 'ncolor': 0, 'iconslight': 'Mkos-Big-Sur', 'iconsdark': 'Mkos-Big-Sur', 'pywal': True, 'pywal_light': True, 'light_blend_multiplier': 1.4, 'dark_blend_multiplier': 2.2, 'on_change_hook': None, 'sierra_breeze_buttons_color': True, 'disable_konsole': False, 'titlebar_opacity': 70, 'titlebar_opacity_dark': 70, 'toolbar_opacity': 85, 'toolbar_opacity_dark': 85, 'konsole_opacity': 85, 'konsole_opacity_dark': 100, 'color': None, 'klassy_windeco_outline': True, 'custom_colors_list': None, 'darker_window_list': None, 'use_startup_delay': False, 'startup_delay': 0, 'plasma_follows_scheme': False, 'pywal_follows_scheme': False, 'main_loop_delay': 1.0, 'screenshot_delay': 900.0, 'once_after_change': False, 'pause_mode': False, 'screenshot_only_mode': False, 'scheme_variant': 5, 'chroma_multiplier': 1.0, 'tone_multiplier': 1.0, 'qdbus_executable': None}
[I] main: main: Wallpaper: org.kde.image (image): /home/xxx/.config/variety/wallpaper/wallpaper-filter-e85ba6d74850fd8a3e3890472130ecf0.jpg
[I] m3_scheme_utils: get_color_schemes: Best colors: 0:#bbbea7 1:#53a7bf 2:#ae9d7e 3:#a4c5bb 4:#f2cba4 5:#c7d3c7 6:#8ec1c2
[I] m3_scheme_utils: get_color_schemes: Using seed: 0:#bbbea7
[I] plasma_utils: apply_color_schemes: Цветовая схема MaterialYouLight успешно задана для использования в Plasma
[I] plasma_utils: set_icons: Icon theme changed to Mkos-Big-Sur: org.kde.plasma.changeicons: Icon theme is already used
[I] titlebar_utils: sierra_breeze_button_colors: Applying SierraBreeze window button colors
Traceback (most recent call last):
  File "/home/xxx/.local/bin/kde-material-you-colors", line 5, in <module>
    from kde_material_you_colors.main import main
  File "/usr/lib/python3.12/site-packages/kde_material_you_colors/main.py", line 507, in <module>
    main()
  File "/usr/lib/python3.12/site-packages/kde_material_you_colors/main.py", line 471, in main
    apply_themes.apply(config, wallpaper, light_mode_watcher.value)
  File "/usr/lib/python3.12/site-packages/kde_material_you_colors/apply_themes.py", line 63, in apply
    titlebar_utils.klassy_windeco_outline_color(schemes, dark_light)
  File "/usr/lib/python3.12/site-packages/kde_material_you_colors/utils/titlebar_utils.py", line 132, in klassy_windeco_outline_color
    outline_color = schemes.get_material_schemes()["light"]["surfaceTint"]
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
KeyError: 'light'
```

**Comment by ShatteredSkies** [comment]
maybe turn off `klassy_windeco_outline` in the config?

**Comment by luisbocanegra** [comment]
> #191 install `python-materialyoucolor` from the AUR

Thanks I completely forgot to  switch from `python-material-color-utilities` to `python-materialyoucolor` in the PKGBUILD. Updated it just now

**Comment by Graninius** [comment]
> maybe turn off `klassy_windeco_outline` in the config?

Yes, it works without it )

> > #191 install `python-materialyoucolor` from the AUR
> 
> Thanks I completely forgot to switch from `python-material-color-utilities` to `python-materialyoucolor` in the PKGBUILD. Updated it just now

Ok )

**Comment by luisbocanegra** [comment]
> ```
> ❯ kde-material-you-colors
> [D] utils: kill_existing: Found previous process in PID file: '43479' killing...
> [D] utils: kill_existing: Process not found, probably ended by someone else
> [I] main: main: ###### STARTED NEW SESSION ######
> [D] main: main: Installed in /usr/lib/python3.12/site-packages/kde_material_you_colors
> [D] config: eval_conf: Config "on_change_hook": empty, using fallback: None
> [D] config: eval_conf: Config "color": empty, using fallback: None
> [D] config: eval_conf: Config "custom_colors_list": empty, using fallback: None
> [D] config: eval_conf: Config "darker_window_list": empty, using fallback: None
> [D] config: eval_conf: Config "qdbus_executable": empty, using fallback: None
> [D] main: main: {'light': True, 'file': None, 'monitor': 0, 'ncolor': 0, 'iconslight': 'Mkos-Big-Sur', 'iconsdark': 'Mkos-Big-Sur', 'pywal': True, 'pywal_light': True, 'light_blend_multiplier': 1.4, 'dark_blend_multiplier': 2.2, 'on_change_hook': None, 'sierra_breeze_buttons_color': True, 'disable_konsole': False, 'titlebar_opacity': 70, 'titlebar_opacity_dark': 70, 'toolbar_opacity': 85, 'toolbar_opacity_dark': 85, 'konsole_opacity': 85, 'konsole_opacity_dark': 100, 'color': None, 'klassy_windeco_outline': True, 'custom_colors_list': None, 'darker_window_list': None, 'use_startup_delay': False, 'startup_delay': 0, 'plasma_follows_scheme': False, 'pywal_follows_scheme': False, 'main_loop_delay': 1.0, 'screenshot_delay': 900.0, 'once_after_change': False, 'pause_mode': False, 'screenshot_only_mode': False, 'scheme_variant': 5, 'chroma_multiplier': 1.0, 'tone_multiplier': 1.0, 'qdbus_executable': None}
> [I] main: main: Wallpaper: org.kde.image (image): /home/xxx/.config/variety/wallpaper/wallpaper-filter-e85ba6d74850fd8a3e3890472130ecf0.jpg
> [I] m3_scheme_utils: get_color_schemes: Best colors: 0:#bbbea7 1:#53a7bf 2:#ae9d7e 3:#a4c5bb 4:#f2cba4 5:#c7d3c7 6:#8ec1c2
> [I] m3_scheme_utils: get_color_schemes: Using seed: 0:#bbbea7
> [I] plasma_utils: apply_color_schemes: Цветовая схема MaterialYouLight успешно задана для использования в Plasma
> [I] plasma_utils: set_icons: Icon theme changed to Mkos-Big-Sur: org.kde.plasma.changeicons: Icon theme is already used
> [I] titlebar_utils: sierra_breeze_button_colors: Applying SierraBreeze window button colors
> Traceback (most recent call last):
>   File "/home/xxx/.local/bin/kde-material-you-colors", line 5, in <module>
>     from kde_material_you_colors.main import main
>   File "/usr/lib/python3.12/site-packages/kde_material_you_colors/main.py", line 507, in <module>
>     main()
>   File "/usr/lib/python3.12/site-packages/kde_material_you_colors/main.py", line 471, in main
>     apply_themes.apply(config, wallpaper, light_mode_watcher.value)
>   File "/usr/lib/python3.12/site-packages/kde_material_you_colors/apply_themes.py", line 63, in apply
>     titlebar_utils.klassy_windeco_outline_color(schemes, dark_light)
>   File "/usr/lib/python3.12/site-packages/kde_material_you_colors/utils/titlebar_utils.py", line 132, in klassy_windeco_outline_color
>     outline_color = schemes.get_material_schemes()["light"]["surfaceTint"]
>                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
> KeyError: 'light'
> ```

Will fix this ASAP thanks.

**Comment by Graninius** [comment]
Hmm, it still hasn't been working with this option enabled (

**Comment by luisbocanegra** [comment]
Fixed the Klassy outline, will be available in the next release.
![outline](https://github.com/luisbocanegra/kde-material-you-colors/assets/15076387/5cd0ae8c-bc1f-461d-9bbb-ece9e0c95ddd)

**Comment by luisbocanegra** [comment]
Hopefully during this weekend.
