### ISSUE TITLE
Error Loading Material You Color Widget

### ISSUE THREAD

**Issue by MohsenGamer11** [luisbocanegra/kde-material-you-colors#209]
So when I came across this program/widget I got excited and wanted to try it out and when I followed the instructions on the GitHub page I came across an Error where you have to install the widget in the widget store it told me that "Unfortunately there was an error loading the widget" 

this is what the error said 

file:///home/(username)/.local/share/plasma/plasmoids/luisbocanegra.kdematerialyou.colors/contents/ui/main.qml:24:34: Type FullRepresentation unavailable

file:///home/(username)/.local/share/plasma/plasmoids/luisbocanegra.kdematerialyou.colors/contents/ui/FullRepresentation.qml:11:1: module "org.kde.kirigami" version 2.20 is not installed

I don't know what to do.

OS Linux Mint
KDE VERSION 5.24.
FRAMEWORKS VERSION 5.92.0

**Comment by luisbocanegra** [comment]
https://github.com/luisbocanegra/kde-material-you-colors/issues/159#issuecomment-1774197635

I recommend you to update to a newer version of Plasma (5.24.7 was released on 14 Oct. 2022)

Why?

Because otherwise you will need to know which module version to import that is supported by Plasma 5.24.7 and doesn't break the widget on plasma 5.27.x (e.g. `import org.kde.kirigami 2.0 as Kirigami` breaks the widget).

If you can give me the minimum version for that module that works on your system and doesn't break on 5.27.x I will happily accept them.

**Comment by MohsenGamer11** [comment]
> [#159 (comment)](https://github.com/luisbocanegra/kde-material-you-colors/issues/159#issuecomment-1774197635)
> 
> I recommend you to update to a newer version of Plasma (5.24.7 was released on 14 Oct. 2022)
> 
> Why?
> 
> Because otherwise you will need to know which module version to import that is supported by Plasma 5.24.7 and doesn't break the widget on plasma 5.27.x (e.g. `import org.kde.kirigami 2.0 as Kirigami` breaks the widget).
> 
> If you can give me the minimum version for that module that works on your system and doesn't break on 5.27.x I will happily accept them.

Thanks for replying how can I update kde 
My knowledge in Linux is unfortunately limited

**Comment by luisbocanegra** [comment]
> Thanks for replying how can I update kde My knowledge in Linux is unfortunately limited

I haven't used Mint/Ubuntu in years so can't give advice on that. I recommend you to ask on Mint forum.

**Comment by MohsenGamer11** [comment]
> > Thanks for replying how can I update kde My knowledge in Linux is unfortunately limited
> 
> I haven't used Mint/Ubuntu in years so can't give advice on that. I recommend you to ask on Mint forum.


Oh ok thanks after a bit of research I found out that Linux mint cinnamon doesn't have good kde support so I have get Linux mint xfce edition.

So if I have the latest version of kde does the widget just works or do I need to do something else  
For example the thing with org.kde.kirigami that you mentioned.

**Comment by luisbocanegra** [comment]
> So if I have the latest version of kde does the widget just works or do I need to do something else For example the thing with org.kde.kirigami that you mentioned.

Yes, it should just work. If you are going to reinstall it may also be worth checking other distributions that ship KDE by default and avoid the trouble of having to install it on top of whatever DE you have https://kde.org/distributions/

Since you are using Mint maybe switching to Kubuntu 24.04 with Plasma 5.27.11 is the best option for you.

Some of the of the other distributions have versions with Plasma 6 in case you want to have a more up-to-date version, just make sure to make an informed decision and backup your important data.

**Comment by MohsenGamer11** [comment]
> > So if I have the latest version of kde does the widget just works or do I need to do something else For example the thing with org.kde.kirigami that you mentioned.
> 
> Yes, it should just work. If you are going to reinstall it may also be worth checking other distributions that ship KDE by default and avoid the trouble of having to install it on top of whatever DE you have https://kde.org/distributions/
> 
> Since you are using Mint maybe switching to Kubuntu 24.04 with Plasma 5.27.11 is the best option for you.
> 
> Some of the of the other distributions have versions with Plasma 6 in case you want to have a more up-to-date version, just make sure to make an informed decision and backup your important data.

thanks a lot, I will look into it and make a good decision 
to ensure the widget works out of the box after installing it?

**Comment by MohsenGamer11** [comment]
hey, it works and it's so awesome I installed Kubuntu in a virtual machine and tested if it works or not and it does work and it works well. Thanks so much for making this possible this kind of thing is also available in Windows and I always wanted it in Linux also.

**Comment by luisbocanegra** [comment]
> Thanks so much for making this possible this kind of thing is also available in Windows and I always wanted it in Linux also.

You're welcome :)

Please note that this is also a feature of Plasma (only the color Plasma scheme part), I started this project when that feature didn't exist but I stick with it as I added more features, but also because I prefer the colors this tool generates.

**Comment by MohsenGamer11** [comment]
> > Thanks so much for making this possible this kind of thing is also available in Windows and I always wanted it in Linux also.
> 
> You're welcome :)
> 
> Please note that this is also a feature of Plasma (only the color Plasma scheme part), I started this project when that feature didn't exist but stick with it as I added more features, but also because I prefer the colors this tool generates.

Thats awesome 👍
