### ISSUE TITLE
Color does not change it only does it once for slideshow wallpaper

### ISSUE THREAD

**Issue by MohsenGamer11** [luisbocanegra/kde-material-you-colors#210]
Hello I have another problem the widget only changes color once for one Wallpaper and when another comes it does not change the color for that wallpaper it just stays the same color as the previous wallpaper. I don't know why this happens I used my own Wallpapers.

Operating System: Arch Linux 
KDE Plasma Version: 6.0.5
KDE Frameworks Version: 6.2.0
Qt Version: 6.7.1
Kernel-Version: 6.9.3-arch1-1 (64-bit)
Graphics Platform: X11
Processors: 16 × AMD Ryzen 7 5800X 8-Core Processor
Memory: 31.3 GiB of RAM
Graphics Processor: AMD Radeon RX 6750 XT

**Comment by luisbocanegra** [comment]
Please run `kde-material-you-colors` from terminal, reproduce the issue and share the output

**Comment by MohsenGamer11** [comment]
ok

**Comment by MohsenGamer11** [comment]
This is the output it's the first wallpaper that it picked up and when I changed the Wallpaper it just stayed in the same color and there was nothing else in the terminal:

[I] main: main: ###### STARTED NEW SESSION ######
[D] main: main: Installed in /usr/lib/python3.12/site-packages/kde_material_you_colors
[D] config: eval_conf: Config "iconslight": empty, using fallback: None
[D] config: eval_conf: Config "iconsdark": empty, using fallback: None
[D] config: eval_conf: Config "on_change_hook": empty, using fallback: None
[D] config: eval_conf: Config "color": empty, using fallback: None
[D] config: eval_conf: Config "custom_colors_list": empty, using fallback: None
[D] config: eval_conf: Config "darker_window_list": empty, using fallback: None
[D] config: eval_conf: Config "qdbus_executable": empty, using fallback: None
[D] main: main: {'light': False, 'file': None, 'monitor': 0, 'ncolor': 0, 'iconslight': None, 'iconsdark': None, 'pywal': True, 'pywal_light': False, 'light_blend_multiplier': 1, 'dark_blend_multiplier': 1, 'on_change_hook': None, 'sierra_breeze_buttons_color': False, 'disable_konsole': False, 'titlebar_opacity': 100, 'titlebar_opacity_dark': 100, 'toolbar_opacity': 100, 'toolbar_opacity_dark': 100, 'konsole_opacity': 100, 'konsole_opacity_dark': 95, 'color': None, 'klassy_windeco_outline': False, 'custom_colors_list': None, 'darker_window_list': None, 'use_startup_delay': False, 'startup_delay': 0, 'plasma_follows_scheme': False, 'pywal_follows_scheme': False, 'main_loop_delay': 1.0, 'screenshot_delay': 900.0, 'once_after_change': True, 'pause_mode': False, 'screenshot_only_mode': False, 'scheme_variant': 5, 'chroma_multiplier': 0.9, 'tone_multiplier': 1.0, 'qdbus_executable': None}
[I] main: main: Wallpaper: org.kde.slideshow (image): /home/(username)/Bilder/Wallpapers for Gaming Pc/cropped-3840-2160-420100.jpg
[I] m3_scheme_utils: get_color_schemes: Best colors: 0:#61758a 1:#e1e5e8
[I] m3_scheme_utils: get_color_schemes: Using seed: 0:#61758a
[I] plasma_utils: apply_color_schemes: Das Farbschema „MaterialYouDark“ wurde erfolgreich für die aktuelle Plasma-Sitzung übernommen.
[D] plasma_utils: set_icons: No icon theme specified.
[I] konsole_utils: get_default_profile: Found default profile 'Profile 1.profile'
[D] konsole_utils: reload_profile: Konsole services (windows) running (1):
[D] konsole_utils: reload_profile: org.kde.konsole-17576 (1 sessions)
[I] pywal_utils: apply_schemes: Setting pywal colors...
[D] pywal_sequences_timeout: send: Sending sequences to /dev/pts/1 /dev/pts/0
[I] pywal_sequences_timeout: send: Set terminal colors.
[I] export: every: Exported all files.
[I] export: every: Exported all user files.
[I] reload: env: Reloaded environment.
[I] kwin_utils: reload: Reloading KWin
 #111417  #b5a8c3  #91b1d1  #90b9de  #9fc0e0  #cabade  #b4c9e0  #e8eaed 
 #a8b4c4  #beb3cb  #9fbbd7  #9fc2e3  #acc8e4  #d0c2e2  #bed0e4  #ebecef 
 #939eab  #7c7488  #637a91  #62809a  #6d859c  #8a809a  #7b8b9c  #9fa2a5

**Comment by luisbocanegra** [comment]
Unfortunately Slideshow wallpaper detection is broken since Plasma 6.0 because it doesn't save the current wallpaper when it changes, like it used to.

There is a new DBus API to query the wallpaper and I will port the backend to use that, hopefully it will be ready over the weekend

**Comment by MohsenGamer11** [comment]
Ok thanks a lot I appreciate It 
Also I'm the guy that wanted to move kubuntu.
Unfortunately kubuntu was a little unstable so I had to move to another distro and Arch is just really good and stable i have experience with Arch Linux so moving here was friendly territory
