### ISSUE TITLE
Autostart not working

### ISSUE THREAD

**Issue by chrostino** [luisbocanegra/kde-material-you-colors#214]
**Describe the bug**
as per title, the program doesn't autostart. `kde-material-you-colors --autostart` gives:
```
kde-material-you-colors --autostart
[W] utils: copy_user_files: Replacing /home/brudda/.config/autostart/kde-material-you-colors.desktop
[D] utils: update_desktop_entry: Updating Exec /home/brudda/.config/autostart/kde-material-you-colors.desktop
[D] utils: update_desktop_entry: Updating link /usr/local/bin/kde-material-you-colors -> /home/brudda/.local/bin/kde-material-you-colors
```
so I went investigating in the mentioned directories and found that the file `/usr/local/bin/kde-material-you-colors` doesn't exist, though I am still able to manually start the program with the terminal or through the widget

**Desktop (please complete the following information):**
 - Operating System: Fedora 40
 - KDE Plasma Version: 6.1.0
 - KDE Frameworks Version: 6.3.0
 - Qt Version: 6.7.1
 - Graphics Platform: Wayland
 - Things in your system that might be relevant: none

**Additional context**
I installed kde-material-you-colors following the instructions for Fedora 40 with the copr repository

**Comment by luisbocanegra** [comment]
Hmm in Fedora the `sysconfig.get_path("scripts")` returns `/usr/local/bin/` but on Arch returns `/usr/bin/` so it needs to be updated so it returns the correct location on both.

https://github.com/luisbocanegra/kde-material-you-colors/blob/0d81481dc34cc9536f748c18949e1d019440f745/src/kde_material_you_colors/settings.py#L16

sysconfig documentation https://docs.python.org/3/library/sysconfig.html
