### ISSUE TITLE
Don't set Konsole transparency or make it an option

### ISSUE THREAD

**Issue by D3SOX** [luisbocanegra/kde-material-you-colors#219]
I want the background transparency to be at 30% but `kde-material-you-colors` always seems to set it to 100% which I don't get because that looks really bad on light backgrounds in almost all cases

**Comment by ShatteredSkies** [comment]
you can change the transparency by setting `konsole_opacity` and `konsole_opacity_dark` in the config file.

**Comment by D3SOX** [comment]
Great, I didn't know that. Then consider this to be a feature request to expose it in the Plasmoid
