### ISSUE TITLE
Breaks colors in some Qt5 apps (QDirStat, KeePassXC)

### ISSUE THREAD

**Issue by D3SOX** [luisbocanegra/kde-material-you-colors#220]
**Describe the bug**
There are a lot of white areas in some Qt5 apps which looks really broken

**To Reproduce**
Launch [KeePassXC](https://keepassxc.org/) and set its theme to "Classic (Platform-native)" or [QDirStat](https://github.com/shundhammer/qdirstat)

**Screenshots**
Can provide after a reboot because KDE refuses to create screenshots (I love the Wayland session....)

**Desktop (please complete the following information):**
Operating System: Arch Linux 
KDE Plasma Version: 6.1.1
KDE Frameworks Version: 6.3.0
Qt Version: 6.8.0
Kernel Version: 6.9.7-zen1-1-zen (64-bit)
Graphics Platform: Wayland

**Comment by luisbocanegra** [comment]
Yes please share some screenshots, tried both and they look as expected for me.

**Comment by D3SOX** [comment]
With Material You
![Screenshot_20240701_080516](https://github.com/luisbocanegra/kde-material-you-colors/assets/24937357/00534136-d890-4e13-9517-467d80347b28)
After switching to Breeze Dark and restarting QDirStat
![Screenshot_20240701_080536](https://github.com/luisbocanegra/kde-material-you-colors/assets/24937357/eb1acda6-fb31-450d-a8d3-73334fd4c61c)

**Comment by luisbocanegra** [comment]
Hmm looks like either some package is missing (maybe `qqc2-desktop-style`?) or interfering with how the colors are set (e.g. kvantum or qt5/6ct)



From another similar issue https://github.com/luisbocanegra/kde-material-you-colors/issues/189#issuecomment-1994623234

> I found the issue: those apps were using the Qt5 framework. To fix it, I installed the breeze5 and plasma5-integration packages, which made them follow the custom theme correctly. Now everything is working as expected.

**Comment by zt64** [comment]
@luisbocanegra Maybe installing `plasma5-integration` should be added to the README? I also had this issue with multiple qt5 programs until I installed that package
