### ISSUE TITLE
Cannot find plasma-changeicons

### ISSUE THREAD

**Issue by ewan58385** [luisbocanegra/kde-material-you-colors#221]
**Describe the bug**
Icons not changing/ kde-matrial-you-colors not finding plasma-changeicons.

**To Reproduce**
1. Run kde-material-you-colors from the terminal to see output.
2. Note this warning: 
     [W] plasma_utils: set_icons: plasma-changeicons wasn't found, can't apply icon themes.

**Expected behavior**
plasma-changeicons is found. I assume it's looking in the wrong directory. On Plasma 6 I believe it's found under:
/usr/lib/x86_64-linux-gnu/libexec/plasma-changeicons

**Desktop (please complete the following information):**
OS: KDE neon 6.0 x86_64 
Host: B460 AORUS PRO AC -CF 
Kernel: 6.5.0-41-generic 
Shell: bash 5.1.16 
DE: Plasma 6.1.2 
WM: KWin 
Theme: Breeze-Dark [GTK2], Breeze [GTK3] 
Icons: breeze-dark [GTK2/3] 
CPU: Intel i7-10700K (16) @ 5.100GHz 
GPU: NVIDIA GeForce RTX 3080

**Comment by luisbocanegra** [comment]
What's the output of `whereis plasma-changeicons`? That's what I am using to find it.

These are the relevant parts of the code where this happens

https://github.com/luisbocanegra/kde-material-you-colors/blob/e3e29041883b10c0ab02bbeacd931216ddb2a035/src/kde_material_you_colors/settings.py#L70

https://github.com/luisbocanegra/kde-material-you-colors/blob/e3e29041883b10c0ab02bbeacd931216ddb2a035/src/kde_material_you_colors/utils/utils.py#L371

https://github.com/luisbocanegra/kde-material-you-colors/blob/e3e29041883b10c0ab02bbeacd931216ddb2a035/src/kde_material_you_colors/utils/plasma_utils.py#L79

**Comment by ewan58385** [comment]
ewanw@ewan-b460aorusproac:~$ whereis plasma-changeicons
plasma-changeicons:

ewanw@ewan-b460aorusproac:~$ locate plasma-changeicons
/usr/lib/x86_64-linux-gnu/libexec/plasma-changeicons


Found the problem; hadn't added libexec to PATH. It works now.
export PATH=$PATH:/usr/lib/x86_64-linux-gnu/libexec

**Comment by luisbocanegra** [comment]
Hmm yeah we need to add that to the readme or maybe in the wiki
