### ISSUE TITLE
Problem with conflicting requests in Fedora 41

### ISSUE THREAD

**Issue by ankenu** [luisbocanegra/kde-material-you-colors#232]
**Describe the bug**
Using the installation via dnf in Fedora 41, there is a problem with conflicting requests.

**To Reproduce**
1. Go to terminal
2. Enter `dnf copr enable luisbocanegra/kde-material-you-colors` and `sudo dnf install kde-material-you-colors`
3. Terminal error output:
```
Problem: conflicting requests
  - nothing provides python3.13dist(materialyoucolor) >= 2.0.8 needed by kde-material-you-colors-1.9.3-1.git.7.1ea3136.fc41.x86_64 from copr:copr.fedorainfracloud.org:luisbocanegra:kde-material-you-colors
You can try to add to command line:
  --skip-broken to skip uninstallable packages
```

**Desktop (please complete the following information):**
 - Operating System: Fedora 41
 - KDE Plasma Version: 6.2.2
 - KDE Frameworks Version: 6.7.0
 - Qt Version: 6.8.0
 - Graphics Platform: Wayland

**Comment by luisbocanegra** [comment]
Hi, can't test in a VM at the moment, have you tried this? https://serverfault.com/questions/1044482/couldnt-upgrade-to-fedora-due-to-error-nothing-provides-python3-8distpython-m

**Comment by ankenu** [comment]
> Hi, can't test in a VM at the moment, have you tried this? https://serverfault.com/questions/1044482/couldnt-upgrade-to-fedora-due-to-error-nothing-provides-python3-8distpython-m

Thanks for the quick response. I don't understand which package I should delete based on this text.

**Comment by ankenu** [comment]
> My bad, you don't have the package installed of course you can't remove it 🤦‍♂️. Is your system up-to-date? If it is I will take a look and fix it over the weekend.

Yep, it's absolutely clean Fedora 41, which I installed yesterday 🙂

**Comment by luisbocanegra** [comment]
Hi again, I triggered to rebuild the packages but the build system keeps throwing unhelpful error messages https://copr.fedorainfracloud.org/coprs/luisbocanegra/kde-material-you-colors/builds/ I will need someone that knows about fedora packaging to fix and maintain it.


But the one at https://software.opensuse.org//download.html?project=home%3Aluisbocanegra&package=kde-material-you-colors builds correctly, can you  try that one instead?

**Comment by SussyGuy35** [comment]
> But the one at https://software.opensuse.org//download.html?project=home%3Aluisbocanegra&package=kde-material-you-colors builds correctly, can you try that one instead?

hi, im get the same problem on fedora 41, when i try that it show this 
![Screenshot_20241109_144339](https://github.com/user-attachments/assets/103846df-0ebf-4f65-8d23-4e2c976b0d50)
kind of scary

**Comment by luisbocanegra** [comment]
> hi, im get the same problem on fedora 41, when i try that it show this
https://github.com/user-attachments/assets/103846df-0ebf-4f65-8d23-4e2c976b0d50
kind of scary

Aren't those old kernel versions? What happens if you update first? I tried in a VM and it installed fine.

[I ran dnf update today and it wanted to remove kernel package? And it also wants to install other kernle package. is it safe to update?](https://www.reddit.com/r/Fedora/comments/1ahamcl/i_ran_dnf_update_today_and_it_wanted_to_remove/)

**Comment by SussyGuy35** [comment]
> > hi, im get the same problem on fedora 41, when i try that it show this
> > https://github.com/user-attachments/assets/103846df-0ebf-4f65-8d23-4e2c976b0d50
> > kind of scary
> 
> Aren't those old kernel versions? What happens if you update first? I tried in a VM and it installed fine.
> 
> [I ran dnf update today and it wanted to remove kernel package? And it also wants to install other kernle package. is it safe to update?](https://www.reddit.com/r/Fedora/comments/1ahamcl/i_ran_dnf_update_today_and_it_wanted_to_remove/)

yes, that those are old kernel versions, my bad. sorry

**Comment by ankenu** [comment]
> Hi again, I tried to rebuild the packages but the build system keeps throwing unhelpful error messages https://copr.fedorainfracloud.org/coprs/luisbocanegra/kde-material-you-colors/builds/ I will need someone that knows about fedora packaging to fix and maintain it.
> 
> But the one at https://software.opensuse.org//download.html?project=home%3Aluisbocanegra&package=kde-material-you-colors builds correctly, can you try that one instead?

Thank you! The second variant works well, but the instruction for installation on the website is wrong. This is the correct steps for Fedora 41:

`sudo dnf config-manager addrepo --from-repofile=https://download.opensuse.org/repositories/home:luisbocanegra/Fedora_41/home:luisbocanegra.repo`

`sudo dnf install kde-material-you-colors`

**Comment by luisbocanegra** [comment]
> > Hi again, I tried to rebuild the packages but the build system keeps throwing unhelpful error messages [copr.fedorainfracloud.org/coprs/luisbocanegra/kde-material-you-colors/builds](https://copr.fedorainfracloud.org/coprs/luisbocanegra/kde-material-you-colors/builds/) I will need someone that knows about fedora packaging to fix and maintain it.
> > But the one at [software.opensuse.org//download.html?project=home%3Aluisbocanegra&package=kde-material-you-colors](https://software.opensuse.org//download.html?project=home%3Aluisbocanegra&package=kde-material-you-colors) builds correctly, can you try that one instead?
> 
> Thank you! The second variant works well, but the instruction for installation on the website is wrong. This is the correct steps for Fedora 41:
> 
> `sudo dnf config-manager addrepo --from-repofile=https://download.opensuse.org/repositories/home:luisbocanegra/Fedora_41/home:luisbocanegra.repo`
> 
> `sudo dnf install kde-material-you-colors`

Yeah, those are automatically generated and needs to be updated, they haven't updated that for dnf5 yet I guess support for fedora 41 is very new, some weeks ago it didn't even build for fedora 40

**Comment by ankenu** [comment]
@luisbocanegra hi. I have the issue again. Package python-pywal16-3.7.2-17.1.x86_64 conflicts with the package python-pywal-3.3.0-8.2.x86_64.

**Comment by luisbocanegra** [comment]
What command did you ran? I am not very familiar with Fedora/dnf but looks like you need to remove python-pywal?

**Comment by luisbocanegra** [comment]
For context, I was packaging `python-pywal` but moved to `python-pywal16` because the former is no longer maintained

**Comment by luisbocanegra** [comment]
The new package was missing `Provides: python-pywal`, can you try again?

https://build.opensuse.org/projects/home:luisbocanegra/packages/python-pywal16/files/python-pywal16.spec?expand=1

**Comment by ankenu** [comment]
@luisbocanegra thank you. It works ✨
