### ISSUE TITLE
Fedora 41 install syntax doesn't work due switch to dnf5

### ISSUE THREAD

**Issue by thafluu** [luisbocanegra/kde-material-you-colors#235]
Just a minor thing, maybe other inexperienced people run into this issue like me.

Following the installation guide from OBS for Fedora 41 (and presumably Rawhide) does not work. Fedora 41 switched from dnf4 to dnf5, hence the command

`dnf config-manager --add-repo https://download.opensuse.org/repositories/home:luisbocanegra/Fedora_41/home:luisbocanegra.repo`

... does not work, dnf5 doesn't have config-manager yet I believe. A workaround is to use dnf3 on Fedora 41

`dnf-3 config-manager --add-repo https://download.opensuse.org/repositories/home:luisbocanegra/Fedora_41/home:luisbocanegra.repo`

**Comment by luisbocanegra** [comment]
Hi, I think this should be reported in https://github.com/openSUSE/software-o-o

**Comment by thafluu** [comment]
Oh sorry, I have no idea how any of this works. I thought the instructions maybe were manually written by the maintainer, but if they are just generated by OBS there is nothing you can do of course, I'll close the issue.

**Comment by luisbocanegra** [comment]
No problem, if you report the problem there please link the issue in a comment here.

A note on the [README](https://github.com/luisbocanegra/plasma-panel-colorizer/blob/main/README.md) can be added in the meantime.
