### ISSUE TITLE
Doesn't work well with ChromiumPywal

### ISSUE THREAD

**Issue by fwinn** [luisbocanegra/kde-material-you-colors#236]
**Describe the bug**
I'm using kde-material-you with pywal v3.3.0. Most things look really nice, for example VS Code. But with [ChromiumPywal](https://github.com/metafates/ChromiumPywal) and Brave in my case, it doesn't look good. I noticed it uses color 11 from pywal as "accent color" and then sets the background of the toolbar to that accent color while the toolbar text color is set to the normal foreground color.
So I don't really know whose responsibility it is :D
It could also be ChromiumPywal's because it's picking a weird color for the toolbar but I also generated a theme directly with pywal and it looked nice.

**To Reproduce**
1. Generate a theme with kde-material-you
2. Make sure it's saved to pywal colors
3. Generate a Chromium theme with ChromiumPywal
4. Enable the theme in Brave

**Expected behavior**
A toolbar which looks something like picture 1

**Screenshots**
This is how it looks with Material you color scheme (1) and with pywal generated theme (2) using the same wallpaper
(1)
![material-you](https://github.com/user-attachments/assets/b25172f4-3777-4d2f-ad67-a88295d195fe)
(2)
![pywal](https://github.com/user-attachments/assets/63ec5158-cea3-4a80-9a28-b0a8e5f0d4c6)

And this is another example with material you, different wallpaper
![material-you2](https://github.com/user-attachments/assets/c69efafd-dcfa-4f8a-b498-f8bca05780af)

**Desktop (please complete the following information):**
 - Operating System: openSUSE Tumbleweed
 - KDE Plasma Version: 6.2.3
 - KDE Frameworks Version: 6.8.0
 - Qt Version: 6.8.0
 - Graphics Platform: X11
 - Other tools involved: pywal version 3.3.0, ChromiumPywal, Brave

**Comment by luisbocanegra** [comment]
Colors 1-15 aren't really suited for background color, in pure pywal they might be but with kde-material-you the colors are brighter to ensure contrast against the background color.

For a proper material you appearance on chrome you can use the colors in `/tmp/kde-material-you-colors-$(whoami).json` instead, should be easy to script with bash + jq or in python.

Or you could darken the colors from ~/.cache/wal/colors.sh

**Comment by fwinn** [comment]
Thank you! The script from ChromiumPywal is pretty simple, so I think I'm going to adapt it for material you and make a pull request so that it'll maybe support material you as well
