### ISSUE TITLE
Doesn't work with plugin org.kde.potd 

### ISSUE THREAD

**Issue by throwaway69420-69420** [luisbocanegra/kde-material-you-colors#29]
I am getting this error
```
kde-material-you-colors -d
Config: {'light': False, 'file': None, 'monitor': 0, 'plugin': 'org.kde.potd', 'ncolor': 0, 'iconslight': None, 'iconsdark': None}
Settting color schemes for 
Error: File "" does not exist
```

**Comment by luisbocanegra** [comment]
It is because Picture of the Day doesn't store the current image, see `~/.config/plasma-org.kde.plasma.desktop-appletsrc` 
```
[Containments][1][Wallpaper][org.kde.potd][General]
FillMode=2
Provider=bing
```
but current wallpapers are stored in `~/.cache/plasma_engine_potd/` with the name of the provider:

```
ls ~/.cache/plasma_engine_potd/
 apod  bing   noaa   simonstalenhag
```
Theorically we could add this special case and monitor the file and providers for changes, I think it might work.

**Comment by luisbocanegra** [comment]
Should be fixed in: [v0.2.1BETA](https://github.com/luisbocanegra/kde-material-you-colors/releases/tag/v0.2.1BETA), **not yet un AUR** please test if all is working:
### Arch 
```sh
mkdir kde-material-you-colors
cd kde-material-you-colors
curl https://raw.githubusercontent.com/luisbocanegra/kde-material-you-colors/testing/PKGBUILD -o PKGBUILD
makepkg -si
```
### Others 
Same instructions from [README](https://github.com/luisbocanegra/kde-material-you-colors#other-distributions)

**Comment by throwaway69420-69420** [comment]
I will test this out today and update you

**Comment by luisbocanegra** [comment]
Closing now, feel free to comment if there are issues and I'll reopen it

**Comment by luisbocanegra** [comment]
Cool, thank you.

**Comment by throwaway69420-69420** [comment]
thanks for the nice project
