### ISSUE TITLE
Colors/algorithm are not as "strong" as the Google Pixel colors and sometimes doesn't even adjust.

### ISSUE THREAD

**Issue by SpxterWohlf** [luisbocanegra/kde-material-you-colors#3]
This could be more of a feature request, and changing the wallpaper to have a drastically different pallet makes a huge difference. However switching between "Honeywave" and my Hiroshi Nagai wallpapers doesn't make a difference (even though honeywave has a pretty different pallet). Even though im using the dark mode flag, it also still seems very bright.

Here is the comparison of my Hiroshi Nagai wallpaper on KDE and on my Pixel 5a

![Screenshot_20220325_140542](https://user-images.githubusercontent.com/33076633/160186646-2fc73c00-8bbe-48a5-b3c6-bf1121ccd291.png)
![Screenshot_20220325-140636](https://user-images.githubusercontent.com/33076633/160186665-37508add-a9d5-4b02-b565-c516819e1444.png)
![Screenshot_20220325-140651](https://user-images.githubusercontent.com/33076633/160186667-a0293b5e-1c36-44dc-bfc3-8339b40e41f1.png)
![Screenshot_20220325-140711](https://user-images.githubusercontent.com/33076633/160186669-3ac1a7ab-be6e-473e-badf-6b809eed460c.png)

**Comment by luisbocanegra** [comment]
The color selection depends directly on the C# implementation how much differs from the original (if any) I am not changing that. My main goal was to have a working implementation where almost all parts of the UI were readable, mixing some colors for contrast, all this without looking too deep into M3 guidelines (tokens), so yeah, colors can be improved. Also the default breeze theme has too much transparency, making selections and some other controls accent color feel way more opaque or what they really are.

**Comment by SpxterWohlf** [comment]
Yeah I think it would be a challenge to mix the colors properly to still have a usable UI. I will personally try to do some research about it in a bit.

**Comment by SpxterWohlf** [comment]
I have updated to the latest version thanks to the suggestion in #10 and this is a lot better in my opinion. 
A couple things I want to note is that the seeds keeps changing every time so restarting the script with the same "color" chosen ends up being different and it's a guessing game to get the same palette again. I also wanna note that in my opinion the light theme is very bright and not tinted enough and it ends up being too white. I think the recent blending of the colors changed the palette selection enough that it feels more "Plasma" like and I enjoy it.

**Comment by luisbocanegra** [comment]
Thanks for your feedback. 
> A couple things I want to note is that the seeds keeps changing every time so restarting the script with the same "color" chosen ends up being different and it's a guessing game to get the same palette again.
 
Yeah, the color extraction is kind of random, even with the most suitable color there is a bit of variation between runs, I don't know if is the same with the original implementations though, I could check that later.
>I also wanna note that in my opinion the light theme is very bright and not tinted enough and it ends up being too white. 

I agree on the light theme, probably this could be improved by adjusting the amount in the blending.

> I think the recent blending of the colors changed the palette selection enough that it feels more "Plasma" like and I enjoy it.

Yes, the contrast improved a lot thanks to the Oklab Colorspace specially when mixing with the default text state colors from Breeze color schemes.

**Comment by luisbocanegra** [comment]
Changed light background tint a bit in: [v0.2.1BETA](https://github.com/luisbocanegra/kde-material-you-colors/releases/tag/v0.2.1BETA), **not yet un AUR** what do you think?
### Arch 
```sh
mkdir kde-material-you-colors
cd kde-material-you-colors
curl https://raw.githubusercontent.com/luisbocanegra/kde-material-you-colors/testing/PKGBUILD -o PKGBUILD
makepkg -si
```
### Others 
Same instructions from [README](https://github.com/luisbocanegra/kde-material-you-colors#other-distributions)

**Comment by SpxterWohlf** [comment]
Sorry for response delay,

I'm on beta 4 I think?,

![image](https://user-images.githubusercontent.com/33076633/163324527-ed6e8df5-b01e-42af-84b2-7bef30b2b199.png)

this is a little more on-par with the pixel, not that this is trying to copy it, however I actually like the current color of the tint versus the pixel because in pixel's dark theme the blacks are mixed with some of the color while the light theme is just white with no color so it feels like im looking at the sun. I do like the current state of the light theme, its not too much but its also not white. I think it would be cool at some point though to have a usage command to determine how much color is blended.

**Comment by luisbocanegra** [comment]
Sorry I edited your comment last time instead of answering (wtf haha), anyway blending amount option was added in latest version if you want to check it

**Comment by SpxterWohlf** [comment]
> Sorry I edited your comment last time instead of answering (wtf haha), anyway blending amount option was added in latest version if you want to check it out.

Alright I've just had the chance to update and try this and this is dope! 😄

Im not sure if there is anything else to provide feedback to "Colors/algorithm are not as "strong" as the Google Pixel colors and sometimes doesn't even adjust" because it has gone above that now!

This is awesome im not sure if there is really anything else needed to be done to make better, it's not exactly "Pixel Like" but its perfect just like how plasma could do it in its own way. 

One thing probably unrelated to this is being able to select a stable color palette instead of the seed changing every time. However im not complain because this is awesome. But I feel like this could be closed now 😁.

Thank you so much for implementing the feedback and making the project. It's made me just a little more happy every time I turn on my computer.

**Comment by luisbocanegra** [comment]
> Alright I've just had the chance to update and try this and this is dope! :smile:
> Im not sure if there is anything else to provide feedback to "Colors/algorithm are not as "strong" as the Google Pixel colors and sometimes doesn't even adjust" because it has gone above that now!

:yum:
> This is awesome im not sure if there is really anything else needed to be done to make better, it's not exactly "Pixel Like" but its perfect just like how plasma could do it in its own way.
> One thing probably unrelated to this is being able to select a stable color palette instead of the seed changing every time. 
> However im not complain because this is awesome. 

Yeah, maybe caching colors but we'll see...
>But I feel like this could be closed now :grin:.

Hooray! :tada:

> Thank you so much for implementing the feedback and making the project. It's made me just a little more happy every time I turn on my computer.

And thanks to you!
