### ISSUE TITLE
Support Generating Light and Dark Scheme at the Same Time

### ISSUE THREAD

**Issue by tuhanayim** [luisbocanegra/kde-material-you-colors#42]
When using both `--light` and `--dark` option, it generates both schemes but sets light theme as default color scheme. In my opinion, instead of requiring `--light` flag for generating light theme, it should generate both even if `--dark` flag used, but color scheme setting should be set with `--light` or `--dark`. *I don't know if pywal supports it, but if it's possible, supporting pywal too would be nice.*

**Comment by luisbocanegra** [comment]
> When using both `--light` and `--dark` option, it generates both schemes but sets light theme as default color scheme. In my opinion, instead of requiring `--light` flag for generating light theme, it should generate both even if `--dark` flag used, but color scheme setting should be set with `--light` or `--dark`.

You're right will change this in the next version.

> _I don't know if pywal supports it, but if it's possible, supporting pywal too would be nice._

With this you mean switching color schemes of terminals and such when switching between the MYouDark and MYouLight color scheme from settings, right?

**Comment by tuhanayim** [comment]
> With this you mean switching color schemes of terminals and such when switching between the MYouDark and MYouLight color scheme from System Settings, right?

Exactly.

**Comment by luisbocanegra** [comment]
Added in [v0.5.0BETA](https://github.com/luisbocanegra/kde-material-you-colors/releases/tag/v0.5.0BETA)
