### ISSUE TITLE
Support running custom scripts after changing color scheme on wallpaper change

### ISSUE THREAD

**Issue by throwaway69420-69420** [luisbocanegra/kde-material-you-colors#46]
**Is your feature request related to a problem? Please describe.**
I use [wal-telegram](https://github.com/guillaumeboehm/wal-telegram/) to set telegram's color scheme based on pywal. It has to be run after every wallpaper change manually.

**Describe the solution you'd like**
I would like a new entry in the config file which allows me to specify a script which runs after setting the color scheme so that custom pywal plugins can work without manual intervention.

**Describe alternatives you've considered**
Modifying desktop file of telegram so that it runs `wal-telegram` during each launch but it becomes too cumbersome as the number of pywal plugins increase.

**Comment by luisbocanegra** [comment]
Added in [v0.5.0BETA](https://github.com/luisbocanegra/kde-material-you-colors/releases/tag/v0.5.0BETA)

**Comment by throwaway69420-69420** [comment]
@luisbocanegra hello, thanks for the update

Do you know how can I run my script which is a separate file like this
```
~/.config/kde-material-you-colors 
❯ tree
.
├── config.conf
└── script.sh
```
please tag me when you reply, also let me know if I should create a separate issue for this, thanks :)

**Comment by luisbocanegra** [comment]
Hi, @throwaway69420-69420, to run a script from any directory and guarantee that it will always work, you should use the absolute path of it, i.e. `/home/USERNAME/.config/kde-material-you-colors/script.sh`

**Comment by throwaway69420-69420** [comment]
I will look into it today
