### ISSUE TITLE
Support for showing output of pywal in case pywal is enabled 

### ISSUE THREAD

**Issue by throwaway69420-69420** [luisbocanegra/kde-material-you-colors#50]
**Is your feature request related to a problem? Please describe.**
Yes, in case pywal is enabled I only get `'pywal': True,` in the first line beginning with `Config:` so it is difficult to see if pywal is actually working or not which can be make debugging the config file more difficult in case there are no visual changes due to pywal.

**Describe the solution you'd like**
An output like 
```
[I] image: Using image unsplash:1065976.
[I] theme: Set theme to _home_USERNAME__cache_plasma_engine_potd_unsplash:1065976_dark_None_None_1.1.0.json.
[I] colors: Found cached colorscheme.
[I] wallpaper: Set the new wallpaper.
[I] sequences: Set terminal colors.

<output of terminal colors here>

[I] export: Exported all files.
[I] export: Exported all user files.
[I] reload: Reloaded environment.
[W] reload: GTK2 reload support requires Python 2.

```
after `kde-material-you-colors` output and before the `on_change_hook` output just like how running `wal -i /home/USERNAME/.cache/plasma_engine_potd/unsplash:1065976` shows its output.

**Comment by luisbocanegra** [comment]
Hmm I think it would be too much text, can it only be the a line indicating that pywal is enabled and generating colors? 
The `<output of terminal colors here>` thing will be repeated with the same colors as they are terminal dependent, unless they are "painted" the same way as the `Best colors:` with `python-colr` and I don't want to add too much, or maybe making it optional with a --verbose flag...
![Screenshot_20220419_210801_python3 kde-material-you-colors py](https://user-images.githubusercontent.com/15076387/164132665-936a652b-b38f-43c3-87a6-f87e3c8b7a90.png)

**Comment by throwaway69420-69420** [comment]
Sorry, I didn't get you

The `--verbose` flag for pywal output seems like a good idea
