### ISSUE TITLE
A gui to change configuration

### ISSUE THREAD

**Issue by luisbocanegra** [luisbocanegra/kde-material-you-colors#58]
### I've started making a Plasma widget for this in https://github.com/luisbocanegra/kde-material-you-colors/pull/146

I have learnt some qml and was able to put it together but if you have more experience with widgets, specially in layouts and handling local files:

* [x] INI for the config, currently using https://doc.qt.io/qt-5/qml-qt-labs-settings-settings.html and shell command to get its location in `${HOME}/.config/kde-material-you-colors/config.conf`, which feels hacky ~~but the only alternative I see is making it configurable. 
 Other thing I noticed is that at (least with [systemdBoot](https://blog.davidedmundson.co.uk/blog/plasma-and-the-systemd-startup/) the default path is `$HOME` so that could be an option if this is always true?~~

  Just found out about [Qt Labs Platform StandardPaths](https://doc.qt.io/qt-5/qtlabsplatform-index.html), so that'll be used instead of a command to locate files

* [x] JSON for the current colors exported by `kde-material-you-colors` to `/tmp/kde-material-you-colors.json` and read using XMLHttpRequest which is going to be deprecated in future Qt ver.) 

  For this I will `cat` the file from executable DataSource for now and will make `kde-material-you-colors` provide it on demand later :)
 
Advice/technical involvement on improving those **and testing!!** would be appreciated! :heart: 

### Status
* [x] Change the colors source (wallpaper or custom)
  * [x] Allow changing changing the main theme color
  * [x] Allow picking other wallpaper colors
* [x] Switch Plasma theme dark/light mode
* [x] Change Konsole/pywal/ksyntaxhighlighting text colors
  * [x] From wallpaper
  * [x] Picking a custom list of colors
	  * [x] Use fallback colors when the option is enabled for firs time
* [x] Switch Konsole/pywal/ksyntaxhighlighting dark/light mode
  * [x] Follow Plasma mode
* [x] Change dark/light color blending multiplier
* [x] Change which screen wallpaper colors are taken from
* [x] Show a message when `kde-material-you-colors` is not running and offer options to start it or view install guide
  * [x] Set custom backend executable location
* [x] Only refresh colors and backend status while widget is open, currently it refresh it every .5 seconds
* [x] Update controls when configuration file is changed

### Advanced settings
* [x] Setting dark/light icon themes
* [x] Custom command for start or wallpaper/dark/light/settings change
* [x] Choosing Konsole profile & opacity
* [x] Specific window decoration/application theme options
  * Sierra breeze buttons color
  * Klassy decoration outline
  * Darker titlebar option
* [x] Changing opacity options
* [x] Changing startup delay

<img src="https://github.com/luisbocanegra/kde-material-you-colors/assets/15076387/fb517690-fa98-4ba8-885c-6ed355673598">

**Comment by luisbocanegra** [comment]
Looks like a Plasmoid may be enough? :eyes: 

![image](https://github.com/luisbocanegra/kde-material-you-colors/assets/15076387/ba2cd7d6-72aa-4a08-a2af-83021d3fde1b)

**Comment by luisbocanegra** [comment]
It works!


https://github.com/luisbocanegra/kde-material-you-colors/assets/15076387/8c3504b0-055f-40fa-905c-db85912a3cf9

**Comment by luisbocanegra** [comment]
Can someone please test https://github.com/luisbocanegra/kde-material-you-colors/pull/146

### Things to test:

* Correctly checks if backend `kde-material-you-colors`is running
* It actually loads respecting the current settings if any
* All the options work
* Behaves correctly if put in multiple panels???
* Updates displayed colors when wallpaper source changes

### Things it doesn't currently do:
* Update controls when changing configuration manually tough IMHO this is low priority at least for the options that are available in the widget for now

**Comment by luisbocanegra** [comment]
@ShatteredSkies I see you're still around. Can you test it? Hope pinging doesn't bother you.

**Comment by ShatteredSkies** [comment]
> * Correctly checks if backend `kde-material-you-colors`is running

:white_check_mark:
> * It actually loads respecting the current settings if any

:white_check_mark:
> * All the options work

:white_check_mark:
> * Behaves correctly if put in multiple panels???

:white_check_mark:
> * Updates displayed colors when wallpaper source changes

:white_check_mark:

sorry for the late response, here are some issues i found:

 * the config file becomes hard to read. (might not be an issue since there is widget)

 * colors in the color selector overflows if there are too many options.

 ![b](https://github.com/luisbocanegra/kde-material-you-colors/assets/56289692/5926c69c-7037-42c0-b872-470a603d2265)

 * does not respect dark/light theme set by Koi.

**Comment by luisbocanegra** [comment]
> sorry for the late response, here are some issues i found:

> * the config file becomes hard to read. (might not be an issue since there is widget)

Yeah, python's configparser is able to keep comments but QML Settings does not :(. I'd like to keep them too. 

The alternative could be exposing the configuration from `kde-material-you-colors` and make the widget "talk" to it so it updates the file instead of the widget. 
This could also mean reading the json file could also be unnecessary if it exposed that too instead 🤯. 
And probably also be used to know the status of the backend more reliably??? 

That could be left for later though.

> * colors in the color selector overflows if there are too many options.

<details>
    <summary>Screenshot</summary>
<img src="https://github.com/luisbocanegra/kde-material-you-colors/assets/56289692/5926c69c-7037-42c0-b872-470a603d2265" alt="widget actions config">
</details>

Can't say I wasn't expecting this to happen. :no_mouth: What resolution/scaling are you using? I think the problem is I didn't give it pixel ratio aware values :sweat_smile:


> * does not respect dark/light theme set by Koi.

Ah yes, there should be an option to follow currently active color  scheme, I'll look into that.

**Comment by ShatteredSkies** [comment]
> 
> Yeah, python's configparser is able to keep comments but QML Settings does not :(. I'd like to keep them too.
> 
> The alternative could be exposing the configuration from `kde-material-you-colors` and make the widget "talk" to it so it updates the file instead of the widget. This could also mean reading the json file could also be unnecessary if it exposed that too instead 🤯. And probably also be used to know the status of the backend more reliably???
> 
> That could be left for later though.
> 

that would be a nice addition for later :)

> What resolution/scaling are you using? I think the problem is I didn't give it pixel ratio aware values 😅

1920x1080, 100% scale.

**Comment by luisbocanegra** [comment]
> 1920x1080, 100% scale.

Hmm, same as me. It should be the pixel ratio thing, if not, I think calculating the size of the remaining area after the text will do which will be required when translated (if ever) anyway.

Thanks for testing BTW.

**Comment by luisbocanegra** [comment]
> does not respect dark/light theme set by Koi.

Done I think. Let me know if it works as expected, requires two new config options so installing both again is necessary.

![image](https://github.com/luisbocanegra/kde-material-you-colors/assets/15076387/afac9d46-bc9a-4f4c-89b3-aa58cabc4578)

**Comment by luisbocanegra** [comment]
> - colors in the color selector overflows if there are too many options.

Should be fixed now, grid columns _should_ automatically wrap based on available width

**Comment by luisbocanegra** [comment]
Also changed the selection indicator and fixed the contrast, looks way nicer now, more like true radio buttons
![image](https://github.com/luisbocanegra/kde-material-you-colors/assets/15076387/a6bb85fb-5ae8-4cfe-a5a8-759e7396aa20)

**Comment by ShatteredSkies** [comment]
> Should be fixed now, grid columns _should_ automatically wrap based on available width

can confirm that it works 👍

**Comment by luisbocanegra** [comment]
Did some changes can you pleas test:

- Widget layout looks right as Desktop/Panel widget and Notification area?
- It continues to read configuration and colors correctly

**Comment by ShatteredSkies** [comment]
> * Widget layout looks right in Desktop/Panel widget and Notification area? Specially when resizing

the minimum width for the widget is a bit awkward, otherwise good.
![xcv](https://github.com/luisbocanegra/kde-material-you-colors/assets/56289692/51e6328a-c6d1-40bd-beff-121354631522)

> * It continues to read configuration and colors correctly

✅

played around with the reload configuration file button, and now it crashes kde-material-colors?

> * And the rest of [A gui to change configuration #58 (comment)](https://github.com/luisbocanegra/kde-material-you-colors/issues/58#issuecomment-1659370583) is still okay 

✅

**Comment by luisbocanegra** [comment]
> the minimum width for the widget is a bit awkward, otherwise good. ![xcv](https://user-images.githubusercontent.com/56289692/258571768-51e6328a-c6d1-40bd-beff-121354631522.png)

Agree, now that the color selector wraps, setting smaller min width should be fine

> played around with the reload configuration file button, and now it crashes kde-material-colors?

Huh? If just when started from the widget then that's expected, the reload destroys the view so it can load new data (and since the command runs as a child of the plasmoid, restarting plasma will also do that), which is not ideal and should be replaced by data-only reload at some point. For now putting anything that doesn't need reload in a separated qml file should get around this I think. 

But if it crashes when is run separately e.g from terminal then there is something else wrong, if there is any meaningful output from python or widget side in journalctl  please share them. 

I'm currently investigating a rare case where the custom colors are reset to black when the widget starts, probably caused by the recent scrollview margin fixes causing some information being lost somewhere.

Thanks again for taking the time and testing it.

**Comment by luisbocanegra** [comment]
> > the minimum width for the widget is a bit awkward, otherwise good.
> 
> Agree, now that the color selector wraps, setting smaller min width should be fine

Done, lmk if something gets cutoff
![image](https://github.com/luisbocanegra/kde-material-you-colors/assets/15076387/3b09ce91-9e0c-4e0d-b223-fb230096a49d)

> If just when started from the widget then that's expected, the reload destroys the view so it can load new data (and since the command runs as a child of the plasmoid, restarting plasma will also do that)

Updated the restart button tooltip indicating this, just in case that I release this without addressing that. :)

> I'm currently investigating a rare case where the custom colors are reset to black when the widget starts, probably caused by the recent scrollview margin fixes causing some information being lost somewhere.

This _should_ be fixed now

**Comment by luisbocanegra** [comment]
Automatic reload is done :) It continuously scans both generated JSON data and the config so only does it when the widget is shown e.g on the desktop or expanded in panel.

https://github.com/luisbocanegra/kde-material-you-colors/assets/15076387/502ca5f9-1ee8-40e8-acd4-99458bfa63b6

**Comment by luisbocanegra** [comment]
Should I try fitting the remaining config options in the widget view or will it be too crowded/heavy?

![image](https://github.com/luisbocanegra/kde-material-you-colors/assets/15076387/caf992ca-7931-4529-8725-32a370df6b52)

**Comment by ShatteredSkies** [comment]
> Should I try fitting the remaining config options in the widget view or will it be too crowded/heavy?

would be bit crowded yeah. don't know much about plasma widgets, but it would be nice if the additional config options were made into collapsibles.

**Comment by luisbocanegra** [comment]
> but it would be nice if the additional config options were made into collapsibles.

Yeah, came up with this, no animation and a bit jumpy but does the job 🙂 

https://github.com/luisbocanegra/kde-material-you-colors/assets/15076387/c7a406d0-6478-4ff2-8650-3f991c00abd8

**Comment by luisbocanegra** [comment]
better

https://github.com/luisbocanegra/kde-material-you-colors/assets/15076387/44049361-a57e-4b0d-b5cb-fc9ba2ba9927

**Comment by luisbocanegra** [comment]
Okay, spent too much time trying to smoothing the transition to the end when the advanced settings appeared, managed to compensate the scrollbar moving the content but still not smooth scroll to the end, the fade kind of does it but it feels more like the whole view should've been reloaded when is not.

Then it occurred to me why not two views (well actually the same but hiding parts)? Solves the crowding and also looks good with the animation, and the same animation could be used when an change in the settings/json is detected too


https://github.com/luisbocanegra/kde-material-you-colors/assets/15076387/be80e10d-36e9-4c7a-a4ca-b801e3c9ec19

**Comment by luisbocanegra** [comment]
Can you please test if the icon theme chooser works correctly?

I am using this shell command to get the list of installed icons:
```sh
# Get a list of installed icon themes as id,name and discard hidden and cursor themes
find /usr/share/icons ~/.local/share/icons -maxdepth 2 -type f -path '*/icons/*/index.theme' ! -path '*/share/icons' ! -exec grep -q '^Hidden=true' {} \; ! -execdir test -d cursors \; -printf '%p\n' | while read line; do echo "$(basename $(dirname $line)),$(grep '^Name=' $line | sed 's/^Name=//')"; done
```


https://github.com/luisbocanegra/kde-material-you-colors/assets/15076387/21f49f85-c2f4-4360-9a2c-097b355195a5

**Comment by luisbocanegra** [comment]
Added most of the remaining options, what are your thoughts of the grouping?

Could not add the plain command option because the QML Settings type escapes special characters, so I am considering dropping support for those in the back-end as I don't want to leave this powerful feature out :)

Also not sure about adding the wallpaper plugin selection, I am considering making it an automatic detection in the back-end with a notification when the active plugin is not supported. After all whether it can work or not depends entirely on the widget storing a readable media source that can provide colors and the back-end knowing where it is.

![image](https://github.com/luisbocanegra/kde-material-you-colors/assets/15076387/7d852df8-08f2-42c5-9d2e-73e4b3099b0a)

**Comment by ShatteredSkies** [comment]
> Can you please test if the icon theme chooser works correctly?

found an issue where the dark icon theme picker always applies selected icon pack regardless of the current light/dark theme.

> Added most of the remaining options, what are your thoughts of the grouping?

looks a little squashed? maybe a bit more padding will do.

also, in my opinion, the "Show advanced settings" button fits better at the bottom of everything, instead of floating on top.

> Also not sure about adding the wallpaper plugin selection, I am considering making it an automatic detection in the back-end with a notification when the active plugin is not supported. After all whether it can work or not depends entirely on the ~widget~ plugin storing a readable media source that can provide colors and the back-end knowing where it is.
>

that sounds awesome, always thought the script changing the wallpaper plugin was a bit frustrating.

**Comment by luisbocanegra** [comment]
> > Can you please test if the icon theme chooser works correctly?
> 
> found an issue where the dark icon theme picker always applies selected icon pack regardless of the current light/dark theme.

Huh? interesting, this also happens on 1.5.1
> 
> > Added most of the remaining options, what are your thoughts of the grouping?
> 
> looks a little squashed? maybe a bit more padding will do.

Yeah, a bit more should help

> also, in my opinion, the "Show advanced settings" button fits better at the bottom of everything, instead of floating on top.

Like at the bottom of both views? I made it floating to make it more discoverable and easier to switch between the two. Is it because is too big? 

> > Also not sure about adding the wallpaper plugin selection, I am considering making it an automatic detection in the back-end with a notification when the active plugin is not supported. After all whether it can work or not depends entirely on the ~widget~ plugin storing a readable media source that can provide colors and the back-end knowing where it is.
> 
> that sounds awesome, always thought the script changing the wallpaper plugin was a bit frustrating.

And it was more of an accidental thing to be honest, just found it handy for quickly testing plugins.

**Comment by ShatteredSkies** [comment]
> > also, in my opinion, the "Show advanced settings" button fits better at the bottom of everything, instead of floating on top.
> 
> Like at the bottom of both views? I made it floating to make it more discoverable and easier to switch between the two. Is it because is too big?

it's supposed to be a 'hidden' option making the UI cleaner, but unnecessarily blocks the view of the UI.
switching between the two interface though... maybe there could be a floating button on the advanced settings view?

**Comment by luisbocanegra** [comment]
> > > also, in my opinion, the "Show advanced settings" button fits better at the bottom of everything, instead of floating on top.
> > 
> > 
> > Like at the bottom of both views? I made it floating to make it more discoverable and easier to switch between the two. Is it because is too big?
> 
> it's supposed to be a 'hidden' option making the UI cleaner, but unnecessarily blocks the view of the UI. switching between the two interface though... maybe there could be a floating button on the advanced settings view?

Maybe, I'll experiment with that after finishing #150

**Comment by luisbocanegra** [comment]
> maybe there could be a floating button on the advanced settings view?

Done, still not sure if I like it, what do you think?

https://github.com/luisbocanegra/kde-material-you-colors/assets/15076387/16074cd0-14cb-4aab-bc0e-66813ea27ffc
