### ISSUE TITLE
Sometimes don't change theme.

### ISSUE THREAD

**Issue by Casul51** [luisbocanegra/kde-material-you-colors#7]
```
Wallpaper changed: /home/casual/Pictures/wallpaper28071.jpg
Setting dark scheme
The requested theme "MaterialYouDark" is already set as the theme for the current Plasma session.
```

It happens 1 of 20-ish tries. 

Operating System: Arch Linux
KDE Plasma Version: 5.24.3
KDE Frameworks Version: 5.92.0
Qt Version: 5.15.3
Kernel Version: 5.16.15-zen1-1-zen (64-bit)
Graphics Platform: Wayland

**Comment by luisbocanegra** [comment]
Should be fixed in [v0.1.0BETA](https://github.com/luisbocanegra/kde-material-you-colors/releases/tag/v0.1.0BETA)
