### ISSUE TITLE
Unreadable text in some places

### ISSUE THREAD

**Issue by mikroffarad** [luisbocanegra/kde-material-you-colors#71]
When I set up perceptible color to maximum (`dark_blend_multiplier = 4.0`), text on buttons is almost unreadable:
![Screenshot_20220821_033322~2.png](https://user-images.githubusercontent.com/42099665/185767629-5391cb88-be24-45ba-9dfa-3ae180ac20a2.png)
![Screenshot_20220821_033612~2.png](https://user-images.githubusercontent.com/42099665/185767654-70d41add-d3e6-4352-a458-c1334d3338f7.png)
It's easy to fix it by manually changing text color of buttons in color-scheme file. However, it's inconvenient to do that on every wallpaper change. 

Another case is when dark mode is enabled, there's some places where in the bright background bright text color remains 

Here's some examples:

- Application Launcher:
![Screenshot_20220821_033054~2.png](https://user-images.githubusercontent.com/42099665/185767401-0f6e308c-3f42-4c89-a5be-012f4b55f7f3.png)
![Screenshot_20220821_033128~2.png](https://user-images.githubusercontent.com/42099665/185767434-f4e8f985-f9ab-41b9-88db-2b94a9b420da.png)
![Screenshot_20220821_033217~2.png](https://user-images.githubusercontent.com/42099665/185767492-35d04fc1-6303-4817-8934-cd5aad70b443.png)

- Dolphin:
![Screenshot_20220821_033153~2.png](https://user-images.githubusercontent.com/42099665/185767469-78a7c017-0fdf-458f-be84-307f46f53328.png)

I tried to change `ForegroundNormal`'s value (133th line of `MaterialYouDark.colors` file) to `#000000`. Text color changes to black, but there's one problem — **black text color is also on dark background**:
![Screenshot_20220821_043217~2.png](https://user-images.githubusercontent.com/42099665/185768275-57ba628f-329f-4cbc-8fca-70cac08abeeb.png)

Is it possible to correct this? I made a little research and realized, that probably there's no rule for ForegroundNormal on bright background. So, is it feature of KDE Plasma's architecture?

Or maybe I configured something wrong?

**Comment by luisbocanegra** [comment]
> When I set up perceptible color to maximum (`dark_blend_multiplier = 4.0`), text on buttons is almost unreadable:

This is a consequence of a poor color decision, buttons should still be dark but with a shade of white so they can stand out but not too white. Will try to fix this

> Another case is when dark mode is enabled, there's some places where in the bright background bright text color remains

Which theme and KDE version are you using?
This is how the default plasma style (that follows color scheme) looks:
![Screenshot_20220820_195118](https://user-images.githubusercontent.com/15076387/185770898-7bb3aadf-f952-428d-accf-a17f05e46449.png)

> - Dolphin:
[image]

This is a bug with [Selection text being ignored](https://bugs.kde.org/show_bug.cgi?id=452884) a workaround could be enabling the option `ChangeSelectionColor=false` which I will add in upcoming version 

> I tried to change `ForegroundNormal`'s value (133th line of `MaterialYouDark.colors` file) to `#000000`. Text color changes to black, but there's one problem — **black text color is also on dark background**:

I don't think plasma themes allow a different color for selected states do they? 

> Is it possible to correct this? I made a little research and realized, that probably there's no rule for ForegroundNormal on bright background. So, is it feature of KDE Plasma's architecture?

Pardon me if I don't understand this you mean a way to detect background and adapt text accordingly? I don't think such feature exists.

**Comment by mikroffarad** [comment]
>     * Which theme and KDE version are you using?
> Sorry for answering after such a long time. Also, sorry I forgot to clarify what my Plasma Style is. I had this problem with the Arc Color Plasma style:
![2022-08-22_14-46](https://user-images.githubusercontent.com/42099665/185882436-503ad6c3-0ec9-44eb-9855-e2f8ebed7599.png)
But when I changed to default Breath Plasma Style, the result satisfied me completely 👌:
![2022-08-22_14-48](https://user-images.githubusercontent.com/42099665/185883327-5c9de56a-1898-4908-a973-8c65e2830f8f.png)
I was just reading [this comment on Reddit](https://www.reddit.com/r/kde/comments/tncff2/comment/i21m45y/?utm_source=share&utm_medium=web2x&context=3) where you wrote what presets you are using: Application Style, Plasma Style, and Window Decoration. You mentioned that there are some changes in Ark Color, but I used vanilla version. Perhaps this had an effect.

If this information is useful to you, here is my configuration:
![image](https://user-images.githubusercontent.com/42099665/185892115-3831a752-497d-4473-b65a-3a0c3888cefb.png)

**Comment by mikroffarad** [comment]
Updated to 0.9.1, works flawlessly🙌

**Comment by mikroffarad** [comment]
>       This is how the default plasma style (that follows color scheme) looks:
![Screenshot_20220820_195118](https://user-images.githubusercontent.com/15076387/185770898-7bb3aadf-f952-428d-accf-a17f05e46449.png)
Sorry for asking too many questions, I would also like to ask: what is the name of this icon pack?

**Comment by luisbocanegra** [comment]
>  I was just reading [this comment on Reddit](https://www.reddit.com/r/kde/comments/tncff2/comment/i21m45y/?utm_source=share&utm_medium=web2x&context=3) where you wrote what presets you are using: Application Style, Plasma Style, and Window Decoration. You mentioned that there are some changes in Ark Color, but I used vanilla version. Perhaps this had an effect. 

Must be it, I probably changed the opacity of that element. 
Like that theme, and many others aren't made having intense colors in mind, same for icon themes, or even some elements of the Lightly Application Style, and sometimes, vanilla KDE. But we're a community and hopefully we can improve that :).

> If this information is useful to you, here is my configuration: ![image](https://user-images.githubusercontent.com/42099665/185892115-3831a752-497d-4473-b65a-3a0c3888cefb.png)

Thanks.

**Comment by luisbocanegra** [comment]
> > ```
> >   This is how the default plasma style (that follows color scheme) looks:
> > ```
> 
> ![Screenshot_20220820_195118](https://user-images.githubusercontent.com/15076387/185770898-7bb3aadf-f952-428d-accf-a17f05e46449.png) Sorry for asking too many questions, I would also like to ask: what is the name of this icon pack?

[Papirus Icons](https://github.com/PapirusDevelopmentTeam/papirus-icon-theme)
With
