### ISSUE TITLE
konsole opacity issue

### ISSUE THREAD

**Issue by ShatteredSkies** [luisbocanegra/kde-material-you-colors#78]
konsole opacity doesn't follow config after color theme changes (material you dark/light)

did not apply konsole_opacity when switching themes

change line 185 in [kde-material-you-colors](https://github.com/luisbocanegra/kde-material-you-colors/blob/main/src/kde-material-you-colors):
```python
utils.konsole_apply_color_scheme(light,options_new['pywal_light'],schemes,options_new['konsole_profile'])
```
to:
```python
utils.konsole_apply_color_scheme(light,options_new['pywal_light'],schemes,options_new['konsole_profile'], konsole_opacity=options_new['konsole_opacity'])
```

**Comment by luisbocanegra** [comment]
Can you please try with the dev branch? It should work there. I changed the logic to monitor specific changes in the configuration, the goal is to run only the needed parts so e.g. you don't regenerate all the colors if only the konsole opacity changed.

That said, I will probably change it again to something cleaner than all those if statements.
