### ISSUE TITLE
Crashes kwin_wayland with latest update (might be unrelated)

### ISSUE THREAD

**Issue by Casul51** [luisbocanegra/kde-material-you-colors#8]
I was using [kde-material-you-colors](https://github.com/luisbocanegra/kde-material-you-colors) for a while and it was working until I updated system (Arch) and running after update resulted to crashes in kwin_wayland.

Operating System: Arch Linux
KDE Plasma Version: 5.24.4
KDE Frameworks Version: 5.92.0
Qt Version: 5.15.3
Kernel Version: 5.17.1-249-tkg-pds (64-bit) (on linux-zen - same)
Graphics Platform: Wayland
Memory: 31.3 GiB of RAM
Graphics Processor: AMD Radeon

journalctl log: https://pastebin.com/EFMCTm03

It may be totally unrelated to your project, since it was working well. Just to make sure that it is my system's/KDE's fault. If it KDE's, then you probably need to create bug report since I have no idea how your code works to specify what causes crash in bug report. Or if you can't reproduce it, just send me instructions to try crash my poor kwin :D

**Comment by Casul51** [comment]
Was working with:

Operating System: Arch Linux
KDE Plasma Version: **5.24.3**
KDE Frameworks Version: 5.92.0
Qt Version: 5.15.3
Kernel Version: 5.16.15-zen1-1-zen (64-bit)
Graphics Platform: Wayland

**Comment by luisbocanegra** [comment]
I can't reproduce it (arch, all updated) tried intel and nvidia, I suspect is unrelated but to discard:
- Does it happen all the time?
- Did you enable the login script?
- If so, does the wayland session work normally after removing the login script?
- If so, does it crash when running from command line in a booted session?

**Comment by Casul51** [comment]
> Does it happen all the time?
With enabled login script it crashes immediately at login. If disabled and started manually kwin may crash at start (of kde-material-you-colors) or at first or 3rd-ish wallpaper change. For details keep reading.

> Did you enable the login script?
Yes. When enabled - Kwin crashes at start.


> If so, does the wayland session work normally after removing the login script?
Yes.


> If so, does it crash when running from command line in a booted session?
Yes. It will crash kwin. BUT if session was already crashed, I have black screen with working kwin, so I can manually restart plasmashell, change start kde-material-you-colors and change wallpaper few times before another crash.

I have few ideas why it happen only for me:
- Triple monitor setup setup with different resolutions.
- Specific configs setup

Gonna check this out

**Comment by Casul51** [comment]
Ladies and Gentlemen, I got him

So, the culprit was... [Bismuth](https://github.com/Bismuth-Forge/bismuth)! Well, almost.

The reason I've had crashes was Bismuth's window decoration, not the extension itself. Exactly by:
~/.config/kwinrc:
```
[org.kde.kdecoration2]
library=org.kde.bismuth.decoration
theme=Bismuth
```

So, it seems that with updates, I've updated Bismuth to the latest version, which contains this bug. Although I believe the issue not only in Bismuth's window decoration, but also something in [kde-material-you-colors](https://github.com/luisbocanegra/kde-material-you-colors), since it was crashing only with it. Can you confirm this?

**Comment by luisbocanegra** [comment]
After installing Bismuth and enabling the [recently added](https://www.github.com/Bismuth-Forge/bismuth/commit/517281e1587692d70cf0093c9901d192cd776f1d) window decorations, can reproduce it (X11 too).
The problem seems to be with changing color schemes when `org.kde.bismuth.decoration` is enabled, you can make it crash even without using [kde-material-you-colors](https://github.com/luisbocanegra/kde-material-you-colors) by switching between the default Breeze color schemes every 5 seconds with the following:
```sh
# Change between BreezeDark and BreezeLight every 5 seconds
while true; do /usr/bin/plasma-apply-colorscheme BreezeDark; sleep 5s; /usr/bin/plasma-apply-colorscheme BreezeLight; sleep 5s; done
```
Changing the color scheme in System Settings can also cause the crash.

So this seems to be an error in bismuth window decorations, I recommend you to report this issue on Bismuth repo.

**Comment by Casul51** [comment]
Cool, gonna report them it.
