### ISSUE TITLE
Generate Both Themes Instead of Setting It

### ISSUE THREAD

**Issue by tuhanayim** [luisbocanegra/kde-material-you-colors#92]
**Is your feature request related to a problem? Please describe.**
When I change wallpaper or theme, kde-material-you-colors always resets the theme, since it generates the color theme and sets generated one as default.

**Describe the solution you'd like**
Instead of using a variable *`(light)`* to generate a color scheme and set it as a theme, just generate them both and let the user select any theme.

**Describe alternatives you've considered**
Don't delete the variable to disable generating light/dark theme, but don't generate the opposite color of it and don't set it as a theme again. *(If `light` environment variable is set to `True` just generate light color scheme, or vice versa.)*

**Additional context**
I'm not sure how pywal will work if the first one being implemented, since pywal will never know what theme the user is using. But it's achievable by running a DBus script to detect the theme, and tell pywal to generate a color scheme for this.

**Comment by luisbocanegra** [comment]
> **Is your feature request related to a problem? Please describe.** When I change wallpaper or theme, kde-material-you-colors always resets the theme, since it generates the color theme and sets generated one as default.
> 
> **Describe the solution you'd like** Instead of using a variable _`(light)`_ to generate a color scheme and set it as a theme, just generate them both and let the user select any theme.
> 
> **Describe alternatives you've considered** Don't delete the variable to disable generating light/dark theme, but don't generate the opposite color of it and don't set it as a theme again. _(If `light` environment variable is set to `True` just generate light color scheme, or vice versa.)_

As is now in #120 it will:
- Generate the both themes, then apply light or dark version based on `light` config and `-l` or ` -d` arguments
- If `light` config and `-l` or ` -d` arguments are not used, it will check for the current Plasma color scheme, (but only between material you versions) and set the corresponding light or dark variant.

> **Additional context** I'm not sure how pywal will work if the first one being implemented, since pywal will never know what theme the user is using. But it's achievable by running a DBus script to detect the theme, and tell pywal to generate a color scheme for this.

- Same for pywal, if is not specified in the config `pywal_light` nor args (`--pywallight, --pywaldark`) it will follow the current plasma theme.

**Comment by luisbocanegra** [comment]
Does that meet your use case? If not please specify in detail the changes you may want

**Comment by tuhanayim** [comment]
Looks fine to me.

**Comment by luisbocanegra** [comment]
Added in https://github.com/luisbocanegra/kde-material-you-colors/releases/tag/v1.5.0
