### ISSUE TITLE
Listen For File Change Instead of Loop

### ISSUE THREAD

**Issue by tuhanayim** [luisbocanegra/kde-material-you-colors#93]
**Is your feature request related to a problem? Please describe.**
Currently, this tool puts itself in a loop that runs every second to check if wallpaper changed or not. And if it's changed, it generates a color scheme.

**Describe the solution you'd like**
Instead of looping, listen for a file change *`(~/.config/plasma-org.kde.plasma.desktop-appletsrc)`* to generate new color scheme. 

**Describe alternatives you've considered**
*None*

**Additional context**
File mentioned above includes some other configs too, so additional check for wallpaper path needed after file change event is triggered.

**Comment by luisbocanegra** [comment]
> **Describe the solution you'd like** Instead of looping, listen for a file change _`(~/.config/plasma-org.kde.plasma.desktop-appletsrc)`_ to generate new color scheme.
> 
> **Additional context** File mentioned above includes some other configs too, so additional check for wallpaper path needed after file change event is triggered.

Excuse the late reply...
While it sounds like a good idea and would have solved the [plasmashell log spam](https://github.com/luisbocanegra/kde-material-you-colors#notes) (can't reproduce anymore in plasma 5.26.2), that file stores panels, widgets and some other configs, so the "watcher" which would still be a loop will have to do extra work having to check whether the changed data is related or not to the wallpaper. I don't know how better that would be performance-wise compared to the current dbus implementation though.

Also will have the same problem with section names mentioned in https://github.com/luisbocanegra/kde-material-you-colors/issues/94#issuecomment-1291090594

Any PR that improves that is very welcomed

**Comment by bentuhana** [comment]
I looked some Plasma apps source code before to check how they detect/apply the change, so It will be more easy. I found a *private (?)* DBus address that probably fires when the mentioned file changes. When I looked for it to test though, I couldn't find such address. So probably file check is the only way to implement it.
